-- SYNAP AI TOOLS — BATCH 2 (200 tools)
-- Run this in Supabase SQL Editor AFTER Batch 1
INSERT INTO public.ai_tools (id,name,slug,category_id,description,icon_emoji,website_url,has_free_tier,is_featured,click_count) VALUES

-- ━━━ EDUCATION & LEARNING ━━━
('khanmigo','Khanmigo','khanmigo','education','AI tutor by Khan Academy that guides students with Socratic questioning.','🎓','https://khanacademy.org/khan-labs',true,true,8200),
('duolingo-ai','Duolingo Max','duolingo-max','education','AI-powered language learning with roleplay conversations and mistake explanations.','🦜','https://duolingo.com',true,true,15000),
('socratic','Socratic by Google','socratic','education','AI homework helper that explains concepts step-by-step using photos.','📚','https://socratic.org',true,true,9800),
('photomath','Photomath','photomath','education','AI math solver that scans equations and explains step-by-step solutions.','📷','https://photomath.com',true,true,12500),
('mathgpt','MathGPT','mathgpt','education','AI math tutor solving algebra, calculus, and statistics problems.','➗','https://mathgpt.ai',true,false,3800),
('brilliant','Brilliant','brilliant','education','Interactive STEM learning platform with AI-adaptive courses in math and science.','💡','https://brilliant.org',false,false,6200),
('coursera-ai','Coursera AI Coach','coursera-ai','education','AI learning assistant integrated into Coursera courses for guidance.','🎓','https://coursera.org',false,false,7400),
('quizlet-ai','Quizlet AI','quizlet','education','AI flashcard and study tool with auto-generated quizzes and explanations.','🃏','https://quizlet.com',true,false,8100),
('anki-ai','Anki AI','anki','education','Spaced repetition flashcard app with AI-generated card suggestions.','🧠','https://ankiweb.net',true,false,4500),
('speechling','Speechling','speechling','education','AI language pronunciation coach with human feedback integration.','🗣️','https://speechling.com',true,false,1800),
('learningmate','LearningMate AI','learningmate','education','AI content creation platform for building e-learning courses and modules.','📋','https://learningmate.com',false,false,1100),
('altitude','Altitude Learning','altitude','education','AI-powered personalized learning platform for K-12 students.','🏔️','https://altitudelearning.com',false,false,900),
('carnegie-learning','Carnegie Learning AI','carnegie','education','AI math tutoring software for middle and high school students.','🏛️','https://carnegielearning.com',false,false,2100),
('century-tech','Century Tech','century','education','AI platform that personalizes learning paths for students and teachers.','📊','https://century.tech',false,false,1400),
('gradescope','Gradescope AI','gradescope','education','AI-assisted grading platform for assignments, exams, and code.','📝','https://gradescope.com',false,false,2800),
('elsa-speak','ELSA Speak','elsa','education','AI English pronunciation coach with real-time accent correction.','🎙️','https://elsaspeak.com',true,false,4200),
('yoodli','Yoodli','yoodli','education','AI speech coach that improves public speaking with real-time feedback.','🗣️','https://yoodli.ai',true,false,2100),
('synthesia-education','Synthesia Edu','synthesia-edu','education','AI video platform for creating interactive educational courses with avatars.','🤖','https://synthesia.io/education',false,false,1900),
('poe-education','Poe for Education','poe-edu','education','Poe platform providing access to multiple AI models for learning.','📱','https://poe.com',true,false,2400),
('gimkit','Gimkit AI','gimkit','education','AI-powered quiz game platform for classroom engagement and learning.','🎮','https://gimkit.com',true,false,3100),

-- ━━━ HEALTHCARE & MEDICAL ━━━
('ada-health','Ada Health','ada','healthcare','AI symptom checker and personal health guide for self-assessment.','🏥','https://ada.com',true,true,7200),
('babylon','Babylon Health','babylon','healthcare','AI health assistant for symptom checking and virtual GP consultations.','💊','https://babylonhealth.com',false,false,4100),
('k-health','K Health','k-health','healthcare','AI primary care app for diagnosing conditions using patient data patterns.','🩺','https://khealth.com',true,false,3800),
('infermedica','Infermedica','infermedica','healthcare','AI symptom checker API powering medical triage applications globally.','🔬','https://infermedica.com',false,false,2100),
('meditron','Meditron','meditron','healthcare','Open medical AI model fine-tuned on clinical guidelines and papers.','⚕️','https://meditron.io',true,false,1400),
('semafind','Sema4.ai Health','sema4','healthcare','AI-powered personalized health insights from DNA and clinical data.','🧬','https://sema4.com',false,false,1200),
('hims-hers','Hims & Hers AI','hims','healthcare','AI-powered telehealth platform for personalized wellness and treatment.','💊','https://forhims.com',false,false,2400),
('doceree','Doceree','doceree','healthcare','AI healthcare marketing platform connecting pharma brands with physicians.','💊','https://doceree.com',false,false,800),
('viz-ai','Viz.ai','viz-ai','healthcare','AI clinical decision support detecting strokes and cardiac events from imaging.','🔍','https://viz.ai',false,false,1600),
('aidoc','Aidoc','aidoc','healthcare','AI medical imaging analysis for radiology workflow prioritization.','🏥','https://aidoc.com',false,false,1900),
('zebra-medical','Zebra Medical Vision','zebra','healthcare','AI radiology platform for detecting chronic diseases from medical scans.','🦓','https://zebra-med.com',false,false,1500),
('paige-ai','Paige AI','paige','healthcare','FDA-approved AI for detecting cancer in pathology slides.','🔬','https://paige.ai',false,false,1800),
('flatiron','Flatiron Health AI','flatiron','healthcare','AI oncology platform analyzing real-world clinical cancer data.','🌐','https://flatiron.com',false,false,2100),
('tempus','Tempus AI','tempus','healthcare','AI platform for precision medicine and clinical data analysis in oncology.','🧬','https://tempus.com',false,false,2400),
('mendel','Mendel.ai','mendel','healthcare','AI clinical data extraction and structuring from medical records.','🧬','https://mendel.ai',false,false,1100),
('subtle-medical','Subtle Medical','subtle','healthcare','AI medical imaging tool that reduces MRI and CT scan acquisition time.','🔬','https://subtlemedical.com',false,false,900),
('livongo','Livongo AI','livongo','healthcare','AI-powered chronic disease management platform for diabetes and hypertension.','💓','https://livongo.com',false,false,1700),
('noom','Noom AI','noom','healthcare','AI weight loss and behavior change program using psychology-based coaching.','⚖️','https://noom.com',false,false,3600),
('calm','Calm AI','calm','healthcare','AI-enhanced meditation and mental wellness app for sleep and anxiety.','🧘','https://calm.com',false,false,5800),
('woebot','Woebot','woebot','healthcare','AI mental health chatbot using CBT techniques for emotional support.','🤖','https://woebothealth.com',true,false,2900),

-- ━━━ FINANCE & ANALYSIS ━━━
('kavout','Kavout','kavout','finance','AI investment intelligence platform with stock scoring and market insights.','📈','https://kavout.com',false,false,1800),
('alphasense','AlphaSense','alphasense','finance','AI financial research platform searching earnings calls, filings, and news.','🔍','https://alpha-sense.com',false,false,2400),
('kensho','Kensho (S&P)','kensho','finance','AI analytics platform for financial markets owned by S&P Global.','📊','https://kensho.com',false,false,2100),
('palantir','Palantir AI','palantir','finance','Enterprise AI platform for data integration and financial decision-making.','🔮','https://palantir.com',false,false,4200),
('quantconnect','QuantConnect','quantconnect','finance','AI algorithmic trading platform for backtesting and live trading strategies.','📉','https://quantconnect.com',true,false,3100),
('alpaca-ai','Alpaca','alpaca-ai','finance','API-first trading platform for algorithmic investing and market automation.','📈','https://alpaca.markets',true,false,2200),
('tradingview-ai','TradingView AI','tradingview-ai','finance','AI-powered chart analysis and trading signals on the world''s top chart platform.','📈','https://tradingview.com',true,false,8900),
('stock-hero','StockHero','stockhero','finance','AI stock trading bot platform running automated strategies 24/7.','🤖','https://stockhero.ai',false,false,1600),
('composer','Composer','composer','finance','No-code AI investment strategy builder with automated rebalancing.','🎵','https://composer.trade',false,false,1900),
('magnifi','Magnifi','magnifi','finance','AI financial advisor for buying stocks, ETFs, and mutual funds with natural language.','🔍','https://magnifi.com',false,false,2100),
('simplywall','Simply Wall St AI','simplywall','finance','AI stock analysis tool visualizing company health with snowflake charts.','📊','https://simplywall.st',true,false,3800),
('finviz','Finviz AI','finviz','finance','AI-enhanced stock screener and financial visualizer for investors.','📉','https://finviz.com',true,false,5200),
('seeking-alpha','Seeking Alpha AI','seeking-alpha','finance','AI-powered investment research and stock analysis community platform.','🔍','https://seekingalpha.com',true,false,6100),
('betterment-ai','Betterment AI','betterment','finance','AI robo-advisor for automated portfolio management and goal-based investing.','💰','https://betterment.com',false,false,4800),
('wealthfront','Wealthfront AI','wealthfront','finance','AI-powered robo-advisor with tax-loss harvesting and financial planning.','💹','https://wealthfront.com',false,false,4200),
('clara-ai','Clara AI','clara-finance','finance','AI financial planning assistant for personal budgeting and investment.','💸','https://clara.chat',true,false,1200),
('cleo','Cleo AI','cleo','finance','AI money coach that tracks spending, roasts your budget, and saves you money.','🤑','https://meetcleo.com',true,true,5600),
('mint-ai','Mint AI','mint','finance','AI personal finance app by Intuit for budgeting and expense tracking.','🌿','https://mint.intuit.com',true,false,6800),
('copilot-money','Copilot Money','copilot-money','finance','AI-powered personal finance app for tracking, budgeting, and investing.','💰','https://copilot.money',false,false,2400),
('quickbooks-ai','QuickBooks AI','quickbooks-ai','finance','AI-powered accounting and bookkeeping software for small businesses.','📚','https://quickbooks.intuit.com',false,false,7200),

-- ━━━ MORE CHAT & AI ASSISTANTS ━━━
('character-ai','Character.AI','character-ai','chat','AI platform for creating and chatting with custom AI characters and personas.','🎭','https://character.ai',true,true,22000),
('replika','Replika','replika','chat','AI companion app for emotional support, friendship, and mental wellness.','💜','https://replika.com',true,false,8400),
('janitorai','JanitorAI','janitorai','chat','AI roleplay chatbot for creating custom AI character conversations.','🤖','https://janitorai.com',true,false,5200),
('spicychat','SpicyChat','spicychat','chat','AI character chat platform with customizable personality and roleplay.','🌶️','https://spicychat.ai',true,false,3800),
('kindroid','Kindroid','kindroid','chat','AI companion with memory and dynamic personality for long-term relationships.','💫','https://kindroid.ai',false,false,2100),
('tavernai','TavernAI','tavernai','chat','Open-source AI storytelling and character roleplay interface.','🍺','https://tavernai.net',true,false,2800),
('oobabooga','Text Generation WebUI','oobabooga','chat','Open-source local LLM runner with extensive model support.','💻','https://github.com/oobabooga',true,false,3200),
('ollama','Ollama','ollama','chat','Run open-source AI models locally on your Mac, Linux, or Windows machine.','🦙','https://ollama.ai',true,false,4800),
('lm-studio','LM Studio','lm-studio','chat','Desktop app for running local LLMs with a friendly interface.','🖥️','https://lmstudio.ai',true,false,4100),
('perplexity-labs','Perplexity Labs','perplexity-labs','chat','Experimental AI research products from Perplexity including reasoning models.','⚗️','https://labs.perplexity.ai',true,false,2900),
('google-aistudio','Google AI Studio','google-aistudio','chat','Free developer platform for prototyping with Gemini models via API.','🔧','https://aistudio.google.com',true,false,5600),
('vertex-ai','Vertex AI','vertex-ai','chat','Google Cloud''s enterprise ML platform for building and deploying AI.','☁️','https://cloud.google.com/vertex-ai',false,false,4800),
('bedrock','Amazon Bedrock','bedrock','chat','AWS platform for accessing foundation models including Claude and Titan.','🪨','https://aws.amazon.com/bedrock',false,false,4200),
('sagemaker','Amazon SageMaker','sagemaker','chat','AWS ML platform for building, training, and deploying ML models.','🔬','https://aws.amazon.com/sagemaker',false,false,3600),
('azure-openai','Azure OpenAI','azure-openai','chat','Microsoft Azure''s managed OpenAI service with enterprise security and compliance.','☁️','https://azure.microsoft.com/ai',false,false,5200),
('claude-api','Claude API','claude-api','chat','Anthropic''s API for embedding Claude into applications and workflows.','🧠','https://anthropic.com/api',false,false,3800),
('inflection-api','Pi API','pi-api','chat','Inflection AI''s API for building empathetic conversational AI apps.','🥧','https://inflection.ai/api',false,false,1400),
('cohere-api','Cohere API','cohere-api','chat','Cohere''s NLP API for text generation, embeddings, and classification.','🔷','https://cohere.ai',false,false,2800),
('ai21','AI21 Studio','ai21','chat','AI21 Labs platform for Jurassic language models and text generation API.','🌿','https://ai21.com',true,false,2100),
('aleph-alpha','Aleph Alpha','aleph-alpha','chat','European sovereign AI company with Luminous language models.','🌟','https://aleph-alpha.com',false,false,1600),

-- ━━━ MORE PRODUCTIVITY & RESEARCH ━━━
('notion-ai','Notion AI','notion-ai','research','AI writing and productivity features embedded inside Notion workspace.','📓','https://notion.so',false,true,16500),
('obsidian-ai','Obsidian AI','obsidian-ai','research','AI plugin ecosystem for Obsidian knowledge management and note-taking.','💎','https://obsidian.md',true,false,5400),
('roam-research','Roam Research AI','roam','research','AI-enhanced networked note-taking tool for researchers and writers.','🗺️','https://roamresearch.com',false,false,3200),
('tana','Tana','tana','research','AI-powered personal knowledge graph for structured thinking and research.','🌿','https://tana.inc',false,false,1800),
('reflect','Reflect','reflect','research','AI note-taking app with backlinking and automatic knowledge connections.','🔮','https://reflect.app',false,false,2400),
('heptabase','Heptabase','heptabase','research','AI visual thinking platform using whiteboard-based note organization.','🗂️','https://heptabase.com',false,false,2100),
('capacities','Capacities','capacities','research','AI knowledge studio for collecting and connecting thoughts and notes.','🧩','https://capacities.io',true,false,1600),
('affine','AFFiNE AI','affine','research','Open-source AI workspace combining docs, whiteboards, and databases.','🔷','https://affine.pro',true,false,1900),
('supernotes','Supernotes','supernotes','research','AI collaborative note-taking system with bidirectional linking.','📝','https://supernotes.app',false,false,1400),
('mymind','MyMind','mymind','research','AI visual bookmark and inspiration manager that auto-tags everything.','🧠','https://mymind.com',false,false,1900),
('elicit-research','Elicit Research','elicit','research','AI research assistant for finding and summarizing academic literature.','🔬','https://elicit.com',true,false,3800),
('consensus-app','Consensus.app','consensus-app','research','AI evidence-based search for finding scientific consensus on topics.','✅','https://consensus.app',true,false,3200),
('undermind','Undermind','undermind','research','AI research tool for deep academic literature search and synthesis.','🔍','https://undermind.ai',false,false,1100),
('paperpal','Paperpal','paperpal','research','AI academic writing assistant for researchers and journal submissions.','📄','https://paperpal.com',true,false,2100),
('jenni-ai','Jenni AI','jenni','research','AI writing assistant for academic essays, research papers, and theses.','✍️','https://jenni.ai',true,false,3400),
('humata','Humata','humata','research','Chat with your PDF documents — AI that answers questions from files.','📄','https://humata.ai',true,false,2800),
('chatpdf','ChatPDF','chatpdf','research','AI tool to upload PDFs and ask questions about the document content.','📑','https://chatpdf.com',true,false,5200),
('pdfai','PDF.ai','pdfai','research','AI PDF reader that summarizes and answers questions from documents.','📋','https://pdf.ai',true,false,3600),
('doctranslate','DocTranslate AI','doctranslate','research','AI document translator supporting 100+ languages with formatting preserved.','🌐','https://doctranslate.io',true,false,1400),
('unriddle','Unriddle','unriddle','research','AI research tool for reading papers faster with instant explanations.','🧩','https://unriddle.ai',true,false,1800),

-- ━━━ MORE CODE & DEV TOOLS ━━━
('github-copilot','GitHub Copilot','github-copilot','code','AI pair programmer by GitHub using OpenAI Codex for code suggestions.','🐱','https://github.com/features/copilot',false,true,18500),
('aws-codewhisperer','Amazon CodeWhisperer','codewhisperer','code','AI code generator by AWS with security scanning and real-time suggestions.','🔶','https://aws.amazon.com/codewhisperer',true,false,5800),
('jetbrains-ai','JetBrains AI','jetbrains-ai','code','AI assistant built into all JetBrains IDEs for code completion and review.','🔧','https://jetbrains.com/ai',false,false,5200),
('android-studio-ai','Android Studio AI','android-studio-ai','code','Google''s AI features in Android Studio for generating and fixing Android code.','📱','https://developer.android.com/studio',true,false,4100),
('xcode-ai','Xcode AI','xcode-ai','code','Apple''s AI coding features in Xcode including Swift assistance and refactoring.','🍎','https://developer.apple.com/xcode',true,false,3800),
('codegpt','CodeGPT','codegpt','code','VS Code extension bringing AI chat and code completion directly to your editor.','🤖','https://codegpt.co',true,false,4600),
('ai-commit','AI Commits','ai-commit','code','AI that generates conventional commit messages by analyzing your staged changes.','📝','https://github.com/Nutlope/aicommits',true,false,2100),
('gpt-engineer','GPT Engineer','gpt-engineer','code','AI that writes an entire codebase from a simple text specification.','⚙️','https://gptengineer.app',true,false,3800),
('mentat','Mentat','mentat','code','AI coding assistant that works inside your terminal with git integration.','🧠','https://mentat.ai',true,false,1900),
('sweep-ai','Sweep AI','sweep','code','AI junior dev that converts GitHub issues into pull requests automatically.','🧹','https://sweep.dev',true,false,2400),
('coderabbit','CodeRabbit','coderabbit','code','AI code reviewer that provides contextual feedback on pull requests.','🐰','https://coderabbit.ai',true,false,2800),
('codeclimate','Code Climate AI','codeclimate','code','AI-assisted technical debt tracking and code quality management platform.','🌡️','https://codeclimate.com',true,false,2100),
('metabob','Metabob','metabob','code','AI code review tool that detects bugs and explains technical debt.','🤖','https://metabob.com',false,false,1500),
('mintlify','Mintlify','mintlify','code','AI documentation writer that generates docs from your codebase automatically.','📖','https://mintlify.com',true,false,2900),
('docstring-ai','Docstring AI','docstring','code','AI that auto-generates docstrings and comments for Python functions.','📝','https://docstring.ai',true,false,1600),
('safurai','Safurai','safurai','code','AI coding assistant for VS Code with chat, refactor, and unit test generation.','🛡️','https://safurai.com',true,false,1800),
('cody-ai','Cody by Sourcegraph','cody','code','AI coding assistant with full codebase awareness for complex repositories.','🐕','https://sourcegraph.com/cody',true,false,2400),
('tabby','Tabby','tabby','code','Open-source self-hosted AI coding assistant with GitHub Copilot parity.','🐱','https://tabby.tabbyml.com',true,false,2100),
('starcoder','StarCoder','starcoder','code','Open-source code LLM from HuggingFace trained on permissive code data.','⭐','https://huggingface.co/bigcode/starcoder',true,false,2600),
('codellama','Code Llama','codellama','code','Meta''s open-source code generation model fine-tuned from Llama 2.','🦙','https://ai.meta.com/llama',true,false,3200),

-- ━━━ MORE IMAGE & CREATIVE TOOLS ━━━
('topaz-ai','Topaz AI','topaz','image','Suite of AI photo enhancement tools: sharpen, denoise, upscale with precision.','🔍','https://topazlabs.com',false,false,5400),
('luminar-ai','Luminar AI','luminar','image','AI photo editor by Skylum with sky replacement, face retouch, and enhancement.','☀️','https://skylum.com',false,false,4100),
('on1-ai','ON1 Photo AI','on1','image','AI photo editing software with noise reduction, sharpening, and masking.','📸','https://on1.com',false,false,2800),
('pixelmator','Pixelmator Pro AI','pixelmator','image','Mac AI photo editor with ML-powered tools for design and retouching.','🎨','https://pixelmator.com',false,false,3200),
('capture-one','Capture One AI','captureone','image','Professional photo editing software with AI masking and color grading.','📷','https://captureone.com',false,false,3600),
('img2go','Img2Go AI','img2go','image','Online AI image tools: converter, compressor, resizer, and enhancer.','🖼️','https://img2go.com',true,false,2100),
('bigjpg','BigJPG','bigjpg','image','AI image upscaler specializing in anime and illustration style images.','🖼️','https://bigjpg.com',true,false,2400),
('let-enhance','Let''s Enhance','letsenhance','image','AI image enhancer for upscaling low-res images to print quality.','✨','https://letsenhance.io',true,false,3100),
('vance-ai','Vance AI','vance','image','Suite of AI image tools including upscale, sharpen, denoise, and bgremoval.','🔧','https://vanceai.com',true,false,2700),
('zyro-ai','Zyro AI Image Generator','zyro','image','Free AI image generator integrated into Zyro website builder.','⚡','https://zyro.com',true,false,1800),
('snowpixel','Snowpixel','snowpixel','image','Multi-modal AI creative platform for images, animations, and music.','❄️','https://snowpixel.app',true,false,1500),
('astria','Astria','astria','image','AI photo generation with custom model training for product and portrait shots.','⭐','https://astria.ai',false,false,2100),
('leapai','Leap AI','leapai','image','API for AI image generation, fine-tuning, and editing in your apps.','🦾','https://tryleap.ai',true,false,1700),
('neural-love','Neural.love','neurallove','image','AI image and video enhancer with upscaling and colorization features.','💕','https://neural.love',true,false,2300),
('deepdreamgenerator','Deep Dream Generator','deepdream','image','AI art tool using Google''s DeepDream neural network for psychedelic art.','🌀','https://deepdreamgenerator.com',true,false,2900),
('dream-by-wombo','Dream by WOMBO','wombo','image','Mobile AI art generator creating images from text prompts quickly.','🎨','https://dream.ai',true,false,4200),
('starryai','StarryAI','starryai','image','AI art generator with full ownership of generated images for creators.','⭐','https://starryai.com',true,false,3600),
('foocus','Fooocus','fooocus','image','Free simplified Stable Diffusion interface inspired by Midjourney quality.','🎯','https://github.com/lllyasviel/Fooocus',true,false,3100),
('mage-space','Mage Space','mage','image','Fast and free AI image generator with Stable Diffusion and SDXL.','🧙','https://mage.space',true,false,2800),
('prompthero','PromptHero','prompthero','image','Community platform for sharing and discovering AI image prompts.','🦸','https://prompthero.com',true,false,2400)

ON CONFLICT (id) DO NOTHING;
