-- SYNAP AI TOOLS — BATCH 11 (more popular tools to reach 1000)
INSERT INTO public.ai_tools (id,name,slug,category_id,description,icon_emoji,website_url,has_free_tier,is_featured,click_count) VALUES

-- ━━━ MORE POPULAR CHAT AI ━━━
('chatgpt-plus','ChatGPT Plus','chatgpt-plus','chat','Premium ChatGPT with GPT-4o, o1 reasoning, DALL-E, and browsing.','🤖','https://chat.openai.com',false,true,85000),
('claude-pro','Claude Pro','claude-pro','chat','Premium Claude with 5x usage, priority access, and Projects.','🧠','https://claude.ai',false,true,35000),
('gemini-adv','Gemini Advanced','gemini-adv','chat','Google Gemini Ultra with 1M context, Gems, and Deep Research.','✨','https://gemini.google.com',false,true,28000),
('perplexity-pro','Perplexity Pro','perplexity-pro','chat','Premium AI search with Claude and GPT-4 for deeper research.','🔍','https://perplexity.ai',false,true,22000),
('typingmind','TypingMind','typingmind','chat','Enhanced ChatGPT interface with plugins and prompt library.','💬','https://typingmind.com',false,false,4200),
('chatbox-app','Chatbox','chatbox','chat','Desktop AI chat client supporting multiple LLM providers.','📦','https://chatboxai.app',true,false,3200),
('jan-ai','Jan AI','jan','chat','Open-source desktop app running AI models locally and privately.','🤖','https://jan.ai',true,false,3800),
('open-webui','Open WebUI','open-webui','chat','Self-hosted web interface for Ollama and OpenAI-compatible APIs.','🌐','https://openwebui.com',true,false,4800),
('koboldai','KoboldAI','koboldai','chat','Open-source AI text generation with customizable storytelling.','🐉','https://koboldai.com',true,false,2200),
('silly-tavern','SillyTavern','silly-tavern','chat','Open-source frontend for AI roleplay with many model backends.','🏰','https://sillytavern.app',true,false,3600),
('text-gen-webui','Text Gen WebUI','text-gen','chat','Gradio web UI for running large language models locally.','💻','https://github.com/oobabooga',true,false,4200),
('localai','LocalAI','localai','chat','Open-source drop-in replacement for OpenAI API running locally.','🏠','https://localai.io',true,false,2800),
('anything-llm','AnythingLLM','anything-llm','chat','All-in-one AI app combining chat, documents, and agents locally.','🤖','https://anythingllm.com',true,false,3400),
('librechat','LibreChat','librechat','chat','Open-source multi-model AI chat interface like ChatGPT.','💬','https://librechat.ai',true,false,2600),
('big-agi','big-AGI','big-agi','chat','Open-source AI chat with multi-model support and personas.','🧠','https://big-agi.com',true,false,1800),

-- ━━━ POPULAR IMAGE TOOLS (more) ━━━
('adobe-express','Adobe Express AI','adobe-express','image','AI design tool with templates, text effects, and generative fill.','🎨','https://adobe.com/express',true,true,12000),
('canva','Canva','canva','image','AI design platform with Magic Studio for images, videos, and docs.','🎨','https://canva.com',true,true,45000),
('pixlr','Pixlr AI','pixlr','image','Free AI photo editor with generative fill and batch editing.','🖼️','https://pixlr.com',true,false,6800),
('photopea','Photopea','photopea','image','Free online Photoshop alternative with AI features.','🎨','https://photopea.com',true,false,8200),
('befunky','BeFunky AI','befunky','image','AI photo editor with batch processing and collage maker.','🎨','https://befunky.com',true,false,3600),
('picsart-ai','Picsart AI','picsart','image','AI photo and video editor with generative tools and templates.','🎨','https://picsart.com',true,true,14000),
('fotor-ai','Fotor AI','fotor','image','AI photo editor with enhancement, background remover, and art.','📸','https://fotor.com',true,false,5200),
('bg-eraser','BGEraser','bgeraser','image','AI background eraser for product and portrait photography.','✂️','https://bgeraser.com',true,false,2400),
('imgcreator','ImgCreator','imgcreator','image','AI image generator with outpainting and design from text.','🖼️','https://imgcreator.zmo.ai',true,false,2800),
('hotpot-ai','Hotpot AI','hotpot','image','AI tools for background removal, upscaling, and art generation.','🍲','https://hotpot.ai',true,false,3200),
('ai-photo-editor','PhotoDirector','photodirector','image','AI photo editor with sky replacement and object removal.','📸','https://cyberlink.com/photodirector',true,false,4200),
('runway-gen3','Runway Gen-3','runway-gen3','image','AI generating high-quality images with Runway Gen-3 Alpha Turbo.','🎬','https://runwayml.com',true,false,6400),
('black-forest','FLUX.1 Pro','flux-pro','image','Black Forest Labs premium image model with highest quality.','⚡','https://blackforestlabs.ai',false,false,5200),
('stability-sd3','Stable Diffusion 3','sd3','image','Latest Stable Diffusion model with improved text and quality.','🎨','https://stability.ai',true,false,7800),
('openart','OpenArt','openart','image','AI image generator with 100+ models and workflow builder.','🎨','https://openart.ai',true,false,4200),

-- ━━━ POPULAR VIDEO TOOLS (more) ━━━
('kling-ai','Kling AI','kling','video','AI video generator by Kuaishou with high-quality motion.','🎬','https://klingai.com',true,false,6800),
('minimax','MiniMax Hailuo','minimax','video','AI video generator creating realistic motion from text prompts.','🎥','https://hailuoai.video',true,false,5200),
('google-veo','Google Veo','google-veo','video','Generative video model from Google for high-quality cinematic clips.','🌙','https://deepmind.google/technologies/veo/',true,false,4800),
('genmo','Genmo','genmo','video','AI video generator with Mochi 1 model for creative content.','🎬','https://genmo.ai',true,false,3200),
('haiper','Haiper','haiper','video','AI video generator by ex-DeepMind team with 2.0 model.','🎥','https://haiper.ai',true,false,2800),
('vidu','Vidu AI','vidu','video','AI video generator by Shengshu Technology with high consistency.','🎬','https://vidu.studio',true,false,2400),
('pixverse','PixVerse','pixverse','video','AI video generator with anime and character animation.','⚡','https://pixverse.ai',true,false,3600),
('morph-studio','Morph Studio','morph','video','AI video creation studio with text-to-video and editing.','🎬','https://morphstudio.com',true,false,2000),
('viggle','Viggle AI','viggle','video','AI making any character move realistically in any video.','🕺','https://viggle.ai',true,false,4200),
('capcut-ai','CapCut AI','capcut','video','Free AI video editor by ByteDance with auto-captions and effects.','✂️','https://capcut.com',true,true,18000),
('clipchamp','Clipchamp AI','clipchamp','video','Microsoft AI video editor with auto-compose and text-to-speech.','🎬','https://clipchamp.com',true,false,6200),
('animaker-ai','Animaker AI','animaker','video','AI animated video maker with characters and whiteboard.','🎭','https://animaker.com',true,false,3400),
('powtoon-ai','Powtoon AI','powtoon','video','AI animated presentation and video maker for business.','🎬','https://powtoon.com',true,false,3800),
('vyond-ai','Vyond AI','vyond','video','AI animated video platform for business communication.','📹','https://vyond.com',false,false,3200),
('rask-ai','Rask AI','rask','video','AI video dubbing and translation in 130+ languages.','🌐','https://rask.ai',true,false,4800),

-- ━━━ POPULAR AUDIO TOOLS (more) ━━━
('suno-v4','Suno v4','suno-v4','audio','Latest Suno AI model with improved vocals and song structure.','🎵','https://suno.com',true,true,15000),
('udio-v2','Udio v2','udio-v2','audio','Updated Udio AI with better music quality and longer tracks.','🎶','https://udio.com',true,false,8200),
('stable-audio','Stable Audio','stable-audio','audio','Stability AI music and sound generator with variable length.','🎵','https://stableaudio.com',true,false,3600),
('musicgen','MusicGen (Meta)','musicgen','audio','Meta open-source AI music generation model running locally.','🎶','https://huggingface.co/facebook/musicgen-large',true,false,2800),
('bark-ai','Bark','bark','audio','Open-source AI text-to-speech with music, effects, and emotion.','🐕','https://github.com/suno-ai/bark',true,false,3200),
('tortoise-tts','Tortoise TTS','tortoise','audio','Open-source high-quality AI text-to-speech with voice cloning.','🐢','https://github.com/neonbjb/tortoise-tts',true,false,2400),
('whisper','OpenAI Whisper','whisper','audio','Open-source AI speech recognition with near-human accuracy.','🔊','https://openai.com/whisper',true,true,8800),
('assembly-ai','AssemblyAI','assembly','audio','AI speech-to-text API with speaker labels and understanding.','🎙️','https://assemblyai.com',true,false,4200),
('deepgram','Deepgram','deepgram','audio','AI speech-to-text API with fastest real-time transcription.','🔊','https://deepgram.com',true,false,3800),
('rev-ai','Rev AI','rev-ai','audio','AI transcription and captioning service with human review option.','📝','https://rev.com',true,false,5200),
('sonix-ai','Sonix','sonix','audio','AI transcription in 40+ languages with smart editing.','🎵','https://sonix.ai',false,false,2600),
('happy-scribe','Happy Scribe','happy-scribe','audio','AI transcription and subtitling with 120+ language support.','😊','https://happyscribe.com',true,false,3200),
('notta-ai','Notta AI','notta','audio','AI meeting transcription with real-time and recorded support.','📝','https://notta.ai',true,false,2800),
('transkriptor','Transkriptor','transkriptor','audio','AI audio and video transcription in 100+ languages.','📄','https://transkriptor.com',true,false,3400),
('audiopen','AudioPen','audiopen','audio','AI converting messy voice notes into clear structured text.','🎙️','https://audiopen.ai',true,false,2200),

-- ━━━ POPULAR RESEARCH TOOLS (more) ━━━
('scite-ai','Scite AI','scite','research','AI citation analysis showing how papers support or contradict.','📊','https://scite.ai',true,false,2800),
('lateral-ai','Lateral AI','lateral','research','AI document analysis finding connections across large document sets.','🔗','https://lateral.io',false,false,1600),
('iris-ai','Iris AI','iris','research','AI research workspace for systematic literature reviews.','🌈','https://iris.ai',false,false,2200),
('litmap','Litmaps','litmaps','research','AI citation mapping visualizing research paper connections.','🗺️','https://litmaps.com',true,false,2400),
('scispace','SciSpace','scispace','research','AI research tool explaining and summarizing scientific papers.','🔬','https://scispace.com',true,false,3600),
('scholarcy','Scholarcy','scholarcy','research','AI summarizing research papers into flashcard knowledge cards.','📝','https://scholarcy.com',true,false,2000),
('zotero-ai','Zotero','zotero','research','Free AI reference manager collecting and organizing sources.','📚','https://zotero.org',true,false,5800),
('mendeley-ai','Mendeley AI','mendeley','research','AI reference manager by Elsevier with collaboration features.','📖','https://mendeley.com',true,false,4200),
('paperpal-2','Paperpal','paperpal-2','research','AI academic writing assistant checking grammar and references.','📄','https://paperpal.com',true,false,2600),
('consensus-2','Consensus','consensus-2','research','AI search engine finding evidence-based answers from research.','✅','https://consensus.app',true,false,3800),
('perplexity-pages','Perplexity Pages','perplexity-pages','research','AI publishing tool creating shareable research articles.','📄','https://perplexity.ai/pages',true,false,2400),
('notebook-lm','NotebookLM','notebook-lm','research','Google AI research assistant analyzing your uploaded documents.','📓','https://notebooklm.google.com',true,true,8400),
('storm-ai','Stanford STORM','storm','research','AI generating Wikipedia-like articles from research queries.','🌪️','https://storm.genie.stanford.edu',true,false,1800),
('genspark','GenSpark','genspark','research','AI search engine generating custom Sparkpages from queries.','⚡','https://genspark.ai',true,false,2200),
('ai-search','SearchGPT','searchgpt','research','OpenAI AI search combining real-time web with language models.','🔍','https://chatgpt.com/search',true,false,6200)

ON CONFLICT (id) DO NOTHING;
