-- SYNAP AI TOOLS — BATCH 1 (200 tools)
-- Run this in Supabase SQL Editor
INSERT INTO public.ai_tools (id,name,slug,category_id,description,icon_emoji,website_url,has_free_tier,is_featured,click_count) VALUES

-- ━━━ CHAT & CONVERSATION ━━━
('poe','Poe','poe','chat','Multi-model AI chat platform by Quora. Access GPT-4, Claude, Gemini and more in one app.','🐦','https://poe.com',true,true,9500),
('pi','Pi','pi','chat','Empathetic AI companion by Inflection AI for personal conversations and support.','🥧','https://pi.ai',true,false,4200),
('cohere-chat','Cohere Chat','cohere-chat','chat','Enterprise-grade AI chat powered by Cohere Command models with RAG support.','🔷','https://cohere.com',true,false,3100),
('you-com','You.com','you-com','chat','AI search assistant combining web search with ChatGPT-style answers.','🔍','https://you.com',true,false,5600),
('phind','Phind','phind','chat','AI search engine and coding assistant specialized for developers.','🔎','https://phind.com',true,false,4800),
('mistral-chat','Le Chat (Mistral)','le-chat','chat','Fast AI chat powered by Mistral AI — open-weight models with European privacy.','🌊','https://chat.mistral.ai',true,false,3900),
('groq','Groq Chat','groq','chat','Ultra-fast AI inference — run Llama, Mixtral at 500+ tokens/second.','⚡','https://groq.com',true,false,3200),
('huggingchat','HuggingChat','huggingchat','chat','Open-source AI chat by Hugging Face with multiple model options.','🤗','https://huggingface.co/chat',true,false,2900),
('kimi','Kimi','kimi','chat','Long-context AI assistant by Moonshot AI supporting 200k tokens.','🌙','https://kimi.moonshot.cn',true,false,2100),
('deepseek-chat','DeepSeek Chat','deepseek-chat','chat','Powerful open-source AI model from DeepSeek with strong reasoning.','🔬','https://chat.deepseek.com',true,true,7200),
('meta-ai','Meta AI','meta-ai','chat','Meta''s AI assistant integrated across WhatsApp, Instagram, and Facebook.','🔮','https://meta.ai',true,true,8100),
('microsoft-copilot','Microsoft Copilot','microsoft-copilot','chat','AI assistant by Microsoft powered by GPT-4 with Bing search integration.','🪟','https://copilot.microsoft.com',true,true,11200),
('google-bard','Google Gemini','google-gemini','chat','Google''s flagship AI assistant with real-time web access and multimodal capabilities.','✨','https://gemini.google.com',true,true,14500),
('inflection','Inflection AI','inflection','chat','AI safety focused company behind Pi AI model for consumer use.','💡','https://inflection.ai',false,false,1800),
('venice-ai','Venice AI','venice-ai','chat','Privacy-focused AI chat that never shares your data with third parties.','🛡️','https://venice.ai',true,false,1500),
('openrouter','OpenRouter','openrouter','chat','API gateway to 100+ AI models including Claude, GPT-4, Llama in one endpoint.','🌐','https://openrouter.ai',true,false,4100),
('together-ai','Together AI','together-ai','chat','Fast inference platform for open-source models — Llama, Mistral, Qwen.','⚙️','https://together.ai',true,false,2800),
('zhipu-ai','Zhipu AI (GLM)','zhipu','chat','Chinese AI company offering GLM-4 model with strong multilingual support.','📖','https://chatglm.cn',true,false,1900),
('qwen','Qwen (Alibaba)','qwen','chat','Alibaba''s Qwen family of models with strong multilingual and coding abilities.','🌏','https://qwen.alibaba.com',true,false,2200),
('grok','Grok (xAI)','grok','chat','Real-time AI by Elon Musk''s xAI with access to X/Twitter data.','🚀','https://grok.x.ai',true,true,9800),

-- ━━━ WRITING & CONTENT ━━━
('quillbot','QuillBot','quillbot','writing','AI paraphrasing and summarization tool used by millions of students and writers.','✏️','https://quillbot.com',true,true,18500),
('wordtune','Wordtune','wordtune','writing','AI writing companion that rewrites sentences for clarity and tone.','📝','https://wordtune.com',true,false,6200),
('grammarly','Grammarly','grammarly','writing','AI-powered writing assistant for grammar, style, and tone corrections.','✅','https://grammarly.com',true,true,22000),
('hemingway','Hemingway Editor','hemingway','writing','Writing editor that highlights complex sentences and suggests simplifications.','🖊️','https://hemingwayapp.com',true,false,4100),
('rytr','Rytr','rytr','writing','AI writing assistant for blog posts, ads, emails in 30+ languages.','🖋️','https://rytr.me',true,false,5800),
('anyword','Anyword','anyword','writing','AI copywriting tool with performance prediction scores for marketing copy.','📊','https://anyword.com',false,false,3400),
('described','Described AI','described','writing','AI tool for generating image alt-text descriptions for accessibility.','👁️','https://described.ai',true,false,900),
('lex','Lex','lex','writing','AI-powered writing tool for long-form content with inline suggestions.','📄','https://lex.page',true,false,2100),
('sudowrite','Sudowrite','sudowrite','writing','AI writing tool specifically for fiction authors and storytellers.','📚','https://sudowrite.com',false,false,2800),
('novelai','NovelAI','novelai','writing','Subscription-based AI storytelling and novel writing platform.','📖','https://novelai.net',false,false,3200),
('shortlyai','Shortly AI','shortlyai','writing','AI writing assistant for long-form blog posts and articles.','⚡','https://shortlyai.com',false,false,1900),
('peppertype','Peppertype AI','peppertype','writing','AI content generation tool for marketing teams and content agencies.','🌶️','https://peppertype.ai',false,false,1400),
('hyperwrite','HyperWrite','hyperwrite','writing','Personal AI writing assistant with real-time autocomplete and research.','💜','https://hyperwrite.com',true,false,2600),
('texta','Texta.ai','texta','writing','AI blog writing tool with SEO optimization and fact-checking built in.','📰','https://texta.ai',true,false,1100),
('ink','INK AI','ink','writing','SEO writing assistant with AI-powered content scoring and optimization.','🖫','https://inkforall.com',true,false,2300),
('contentbot','ContentBot','contentbot','writing','AI content marketing platform with workflow automation for agencies.','🤖','https://contentbot.ai',false,false,1700),
('longshot','LongShot AI','longshot','writing','AI writing tool that fact-checks content in real-time while generating.','🎯','https://longshot.ai',false,false,1500),
('nichesss','Nichesss','nichesss','writing','AI tool for generating niche topic ideas, hooks, and ad copy.','🎪','https://nichesss.com',false,false,800),
('storychief','StoryChief','storychief','writing','Content marketing platform with AI writing and multi-channel publishing.','📢','https://storychief.io',false,false,1300),
('writerly','Writerly AI','writerly','writing','AI content generator for e-commerce product descriptions and listings.','🛍️','https://writerly.ai',false,false,950),

-- ━━━ IMAGE GENERATION ━━━
('ideogram','Ideogram','ideogram','image','AI image generator excellent at rendering accurate text inside images.','💬','https://ideogram.ai',true,true,7400),
('adobe-firefly','Adobe Firefly','adobe-firefly','image','Adobe''s AI image generation integrated into Creative Cloud tools.','🔥','https://firefly.adobe.com',true,true,9800),
('canva-ai','Canva AI','canva-ai','image','AI image generator and design tools integrated within Canva platform.','🎨','https://canva.com',true,true,21000),
('nightcafe','NightCafe','nightcafe','image','AI art generator with multiple models including Stable Diffusion and DALL-E.','🌙','https://nightcafe.studio',true,false,5500),
('dreamstudio','DreamStudio','dreamstudio','image','Official Stable Diffusion web interface by Stability AI.','🎭','https://dreamstudio.ai',false,false,6100),
('playground-ai','Playground AI','playground-ai','image','Free AI image generator with advanced editing and canvas features.','🛝','https://playgroundai.com',true,false,5800),
('bluewillow','BlueWillow','bluewillow','image','Free Midjourney alternative using Discord for AI image generation.','🔵','https://bluewillow.ai',true,false,3100),
('bing-image','Bing Image Creator','bing-image','image','Microsoft''s free DALL-E 3 powered image generator via Bing.','🖼️','https://bing.com/images/create',true,true,12000),
('getimg','getimg.ai','getimg','image','Advanced AI image platform with training, editing, and generation tools.','🎞️','https://getimg.ai',true,false,3400),
('tensor.art','Tensor.art','tensor-art','image','Community platform for sharing and running Stable Diffusion models.','🎆','https://tensor.art',true,false,2800),
('civitai','CivitAI','civitai','image','Largest repository for Stable Diffusion models, LoRAs, and AI art.','🏛️','https://civitai.com',true,false,7200),
('seaart','SeaArt','seaart','image','AI art generator with large model library and anime-style support.','🌊','https://seaart.ai',true,false,3600),
('piclumen','Piclumen','piclumen','image','AI image generator with ultra-realistic photography-style outputs.','📸','https://piclumen.com',true,false,2100),
('krea','Krea AI','krea','image','Real-time AI image generation and upscaling with live canvas editing.','✨','https://krea.ai',true,false,2900),
('magnific','Magnific AI','magnific','image','AI image upscaler and enhancer with hallucination-based detail generation.','🔍','https://magnific.ai',false,false,3800),
('clipdrop','ClipDrop','clipdrop','image','Suite of AI image editing tools: remove background, upscale, relight.','✂️','https://clipdrop.co',true,false,5200),
('remove-bg','Remove.bg','remove-bg','image','AI-powered background remover — instant results with one click.','🪄','https://remove.bg',true,false,14000),
('photoroom','PhotoRoom','photoroom','image','AI photo editor for product photography and background replacement.','📷','https://photoroom.com',true,false,6100),
('fotor','Fotor AI','fotor','image','Online AI photo editor and image generator for non-designers.','🖼️','https://fotor.com',true,false,4500),
('stockimg','Stockimg.ai','stockimg','image','AI tool for generating stock photos, book covers, banners, and logos.','🖼️','https://stockimg.ai',true,false,2200),

-- ━━━ CODE & DEVELOPMENT ━━━
('cursor','Cursor','cursor','code','AI-first code editor with GPT-4 integration for pair programming.','🖱️','https://cursor.sh',true,true,12400),
('replit-ai','Replit AI','replit-ai','code','AI coding assistant built into Replit''s online IDE for all languages.','🌀','https://replit.com',true,true,8900),
('codeium','Codeium','codeium','code','Free AI code completion and chat for 70+ programming languages.','💚','https://codeium.com',true,true,7600),
('supermaven','Supermaven','supermaven','code','Fastest AI code completion with 300k token context window for large codebases.','⚡','https://supermaven.com',true,false,2800),
('continue-dev','Continue','continue','code','Open-source AI code assistant that works with VS Code and JetBrains IDEs.','🔄','https://continue.dev',true,false,3100),
('aider','Aider','aider','code','AI pair programmer in the terminal — edit code across entire git repos.','🤝','https://aider.chat',true,false,2400),
('v0','v0 by Vercel','v0','code','AI frontend code generator that produces React/shadcn components instantly.','▲','https://v0.dev',true,true,9200),
('bolt','Bolt.new','bolt','code','Full-stack AI web app builder running entirely in the browser.','⚡','https://bolt.new',true,true,11500),
('lovable','Lovable','lovable','code','AI that builds full-stack React apps from text descriptions.','❤️','https://lovable.dev',true,true,8700),
('devin-ai','Devin AI','devin','code','World''s first AI software engineer that autonomously completes coding tasks.','🤖','https://devin.ai',false,true,14200),
('cosine','Cosine Genie','cosine','code','AI codebase expert that understands your entire repository context.','🔷','https://cosine.sh',false,false,1900),
('blackbox-ai','Blackbox AI','blackbox','code','AI coding assistant with code search and real-time autocomplete.','⬛','https://blackbox.ai',true,false,4200),
('pieces','Pieces for Developers','pieces','code','AI-powered developer tools for saving, sharing, and reusing code snippets.','🧩','https://pieces.app',true,false,2100),
('snyk','Snyk Code','snyk','code','AI-powered security scanning tool that finds and fixes code vulnerabilities.','🛡️','https://snyk.io',true,false,5800),
('codacy','Codacy','codacy','code','Automated code review platform with AI-powered quality analysis.','📋','https://codacy.com',true,false,2900),
('sourcegraph','Sourcegraph Cody','cody','code','AI coding assistant with enterprise codebase search and understanding.','🔭','https://sourcegraph.com',true,false,3400),
('e2b','E2B','e2b','code','Cloud runtime for AI coding agents — secure sandboxed code execution.','📦','https://e2b.dev',true,false,1700),
('warp','Warp Terminal','warp','code','AI-powered terminal with built-in AI command suggestions and debugging.','🖥️','https://warp.dev',true,false,4600),
('fronty','Fronty','fronty','code','AI that converts images and screenshots into HTML/CSS code.','🖼️','https://fronty.com',true,false,2300),
('durable','Durable','durable','code','AI website builder that creates full websites in 30 seconds.','🏗️','https://durable.co',false,false,3700),

-- ━━━ VIDEO GENERATION ━━━
('sora','Sora (OpenAI)','sora','video','OpenAI''s text-to-video model generating high-quality HD video clips.','🎬','https://sora.com',false,true,18500),
('kling','Kling AI','kling','video','Chinese AI video generator producing realistic 2-minute video clips.','🎥','https://klingai.com',true,true,9200),
('pika','Pika Labs','pika','video','AI video generation and editing tool for short creative videos.','⚡','https://pika.art',true,true,7800),
('luma-dream','Luma Dream Machine','luma','video','AI video generator from images and text with cinematic quality.','🌟','https://lumalabs.ai/dream-machine',true,true,8400),
('morph-studio','Morph Studio','morph','video','AI video generation platform for professional quality output.','🔮','https://morphstudio.com',true,false,2100),
('haiper','Haiper','haiper','video','AI video generation tool for creating videos from text or image prompts.','💫','https://haiper.ai',true,false,1800),
('invideo-ai','InVideo AI','invideo','video','AI video creator for YouTube, ads, and social media with voiceover.','📹','https://invideo.io',true,true,6700),
('pictory','Pictory','pictory','video','AI video creator that converts long-form content into short branded clips.','🎞️','https://pictory.ai',false,false,4100),
('descript','Descript','descript','video','AI video and podcast editor with word-level editing and voice cloning.','✂️','https://descript.com',true,true,7900),
('captions-ai','Captions AI','captions','video','AI video creator with auto-captions, avatar dubbing, and eye contact fix.','💬','https://captions.ai',true,false,4800),
('opus-clip','Opus Clip','opus-clip','video','AI that cuts long videos into viral short clips for social media.','✂️','https://opus.pro',true,true,8200),
('vidyo-ai','Vidyo.ai','vidyo','video','AI video repurposing tool to turn long videos into short social clips.','📱','https://vidyo.ai',true,false,3600),
('veed','Veed.io','veed','video','Online AI video editor with subtitles, avatars, and dubbing features.','🎬','https://veed.io',true,false,5400),
('fliki','Fliki','fliki','video','AI video creation from text with realistic voices and stock footage.','🦜','https://fliki.ai',true,false,3100),
('colossyan','Colossyan','colossyan','video','AI avatar video creator for corporate training and e-learning content.','👤','https://colossyan.com',false,false,2200),
('hour-one','Hour One','hour-one','video','AI human avatar video platform for business communication.','⏰','https://hourone.ai',false,false,1900),
('deepbrain','DeepBrain AI','deepbrain','video','AI video studio with lifelike human avatars for corporate use.','🧠','https://deepbrain.io',false,false,2100),
('elai-io','Elai.io','elai','video','AI video generation platform with 80+ languages and custom avatars.','🌐','https://elai.io',false,false,1700),
('stable-video','Stable Video Diffusion','stable-video','video','Stability AI''s open-source video generation model for researchers.','🎞️','https://stability.ai/stable-video',true,false,3800),
('wanvideo','Wan Video','wan-video','video','Open-source video generation model from Alibaba for cinematic clips.','🎭','https://wanvideo.ai',true,false,2400),

-- ━━━ AUDIO & VOICE ━━━
('udio','Udio','udio','audio','AI music generator creating full songs from text descriptions.','🎵','https://udio.com',true,true,8900),
('aiva','AIVA','aiva','audio','AI music composer for film, games, and media soundtracks.','🎹','https://aiva.ai',true,false,4200),
('soundraw','Soundraw','soundraw','audio','AI royalty-free music generator for creators with infinite customization.','🎸','https://soundraw.io',true,false,3600),
('beatoven','Beatoven.ai','beatoven','audio','AI music tool generating mood-based background music for videos.','🥁','https://beatoven.ai',true,false,2400),
('boomy','Boomy','boomy','audio','AI music creation platform — make songs in seconds and distribute them.','🎤','https://boomy.com',true,false,2100),
('loudly','Loudly','loudly','audio','AI music platform for generating and customizing royalty-free tracks.','📢','https://loudly.com',true,false,1800),
('voice-ai','Voice.ai','voice-ai','audio','Real-time AI voice changer and cloning tool for gamers and streamers.','🎙️','https://voice.ai',true,false,4100),
('speechify','Speechify','speechify','audio','AI text-to-speech app that reads any content aloud with natural voices.','🔊','https://speechify.com',true,true,9200),
('natural-reader','NaturalReader','naturalreader','audio','Online text-to-speech tool with AI voices for documents and ebooks.','📖','https://naturalreaders.com',true,false,5600),
('whisper-ai','Whisper (OpenAI)','whisper','audio','Open-source speech recognition model by OpenAI with multilingual support.','🎤','https://openai.com/research/whisper',true,false,5800),
('deepgram','Deepgram','deepgram','audio','API-first speech recognition and voice AI platform for developers.','🔮','https://deepgram.com',true,false,3200),
('descript-overdub','Overdub by Descript','overdub','audio','AI voice cloning that creates realistic text-to-speech in your own voice.','🎭','https://descript.com/overdub',false,false,2800),
('resemble','Resemble AI','resemble','audio','Real-time AI voice cloning and synthesis for enterprises and creators.','👥','https://resemble.ai',false,false,2100),
('listening','Listening.com','listening','audio','AI podcast and audio summarizer that gives you key insights fast.','🎧','https://listening.com',true,false,900),
('adobe-podcast','Adobe Podcast','adobe-podcast','audio','AI audio enhancement tool that makes any microphone sound professional.','🎙️','https://podcast.adobe.com',true,false,5100),
('podcastle','Podcastle','podcastle','audio','Browser-based podcast creation platform with AI noise removal and editing.','🏰','https://podcastle.ai',true,false,2700),
('auphonic','Auphonic','auphonic','audio','AI audio post-production for leveling, noise reduction, and mastering.','🔈','https://auphonic.com',true,false,2300),
('krisp','Krisp','krisp','audio','AI noise cancellation app for calls and recordings in real-time.','🔇','https://krisp.ai',true,true,7400),
('cleanvoice','CleanVoice AI','cleanvoice','audio','AI that removes filler words, stuttering, and silence from podcast recordings.','✨','https://cleanvoice.ai',true,false,1900),
('riffusion','Riffusion','riffusion','audio','AI music generation via stable diffusion spectrograms — unique model.','🌊','https://riffusion.com',true,false,2200),

-- ━━━ RESEARCH & PRODUCTIVITY ━━━
('consensus','Consensus','consensus','research','AI search engine for scientific research papers with evidence summaries.','🔬','https://consensus.app',true,true,6800),
('semantic-scholar','Semantic Scholar','semantic-scholar','research','Free academic search engine with AI-powered paper recommendations.','📚','https://semanticscholar.org',true,false,5100),
('connected-papers','Connected Papers','connected-papers','research','Visual tool to find and explore related academic papers in a graph.','🕸️','https://connectedpapers.com',true,false,3400),
('scite','Scite.ai','scite','research','AI tool showing how research papers have been cited in other studies.','📊','https://scite.ai',true,false,2800),
('lateral','Lateral','lateral','research','AI research tool for organizing and synthesizing academic literature.','📋','https://lateral.io',false,false,1500),
('iris-ai','Iris.ai','iris','research','AI research assistant for finding and analyzing scientific papers.','🌸','https://iris.ai',false,false,1200),
('research-rabbit','ResearchRabbit','researchrabbit','research','Free academic discovery tool connecting related papers and authors.','🐰','https://researchrabbit.ai',true,false,2900),
('explainpaper','ExplainPaper','explainpaper','research','Upload academic papers and ask AI to explain complex sections simply.','📄','https://explainpaper.com',true,false,2100),
('paperdigest','Paper Digest','paperdigest','research','AI that summarizes academic research papers in simple language.','📝','https://paper-digest.com',true,false,1100),
('txyz','TXYZ.ai','txyz','research','AI research assistant for literature review and paper summarization.','🔭','https://txyz.ai',true,false,900),
('scholarai','ScholarAI','scholarai','research','ChatGPT plugin for searching and reading scientific papers.','🎓','https://scholarai.io',true,false,1600),
('bing-copilot','Bing Copilot','bing-copilot','research','Microsoft''s AI search with real-time web citations and summaries.','🔍','https://bing.com',true,true,15000),
('mem','Mem AI','mem','research','AI-powered note-taking that automatically organizes your knowledge.','🧠','https://mem.ai',false,false,2400),
('logseq','Logseq AI','logseq','research','Open-source knowledge management tool with AI writing assistant.','📓','https://logseq.com',true,false,3100),
('readwise','Readwise Reader','readwise','research','AI reading tool that highlights, summarizes, and resurfaces key insights.','📖','https://readwise.io',false,false,4200),
('omnivore','Omnivore','omnivore','research','Free open-source read-it-later app with AI summaries and highlights.','📚','https://omnivore.app',true,false,1800),
('glasp','Glasp','glasp','research','Social web highlighter with AI summaries for online articles.','🖊️','https://glasp.co',true,false,1600),
('speechlab','SpeechLab','speechlab','research','AI transcription and translation for videos and audio in 100+ languages.','💬','https://speechlab.ai',false,false,900),
('otter-ai','Otter.ai','otter','research','AI meeting transcription and notes with action items and summaries.','🦦','https://otter.ai',true,true,8900),
('fireflies','Fireflies.ai','fireflies','research','AI meeting assistant for recording, transcribing, and searching meetings.','🦋','https://fireflies.ai',true,true,7600),

-- ━━━ SEO & MARKETING ━━━
('clearscope','Clearscope','clearscope','marketing','AI content optimization platform for SEO with competitor analysis.','🎯','https://clearscope.io',false,false,2800),
('frase','Frase','frase','marketing','AI SEO tool for content research, outlining, and optimization.','📊','https://frase.io',false,false,3200),
('neuronwriter','NeuronWriter','neuronwriter','marketing','AI content editor with NLP-powered SEO optimization and competitor analysis.','🧠','https://neuronwriter.com',false,false,2100),
('writeseo','WriteSEO','writeseo','marketing','AI article generator optimized for search engine rankings.','✍️','https://writeseo.com',false,false,1100),
('dashword','Dashword','dashword','marketing','AI content optimization tool with keyword tracking and NLP analysis.','📈','https://dashword.com',false,false,1400),
('type-studio','Type Studio','type-studio','marketing','AI tool for repurposing podcast and video content into blog posts.','⌨️','https://typestudio.co',true,false,1200),
('hootsuite-ai','Hootsuite AI','hootsuite-ai','marketing','AI social media scheduling and content creation for brands.','🦉','https://hootsuite.com',false,false,4100),
('buffer-ai','Buffer AI','buffer-ai','marketing','AI-powered social media management with content suggestions.','📱','https://buffer.com',true,false,3600),
('predis','Predis.ai','predis','marketing','AI social media content creator with competitor analysis.','🎯','https://predis.ai',true,false,2700),
('recently-ai','Recently.ai','recently','marketing','AI that repurposes long content into social posts, newsletters, and ads.','⏱️','https://recently.ai',false,false,900),
('vidiq-ai','VidIQ AI','vidiq','marketing','AI YouTube growth tool with keyword research and video optimization.','📹','https://vidiq.com',true,false,5200),
('tubebuddy','TubeBuddy AI','tubebuddy','marketing','YouTube certified channel management tool with AI SEO features.','🎬','https://tubebuddy.com',true,false,4800),
('adcreative','AdCreative.ai','adcreative','marketing','AI ad generator creating high-converting banners, copy, and videos.','📢','https://adcreative.ai',false,false,3400),
('pencil','Pencil AI','pencil','marketing','AI ad creative generator that predicts performance before launch.','✏️','https://trypencil.com',false,false,2100),
('smartly','Smartly.io','smartly','marketing','AI-powered advertising automation for Meta, TikTok, and Google ads.','💡','https://smartly.io',false,false,2800),
('dragonfly','Dragonfly AI','dragonfly','marketing','AI visual attention prediction for ads and landing page optimization.','🐉','https://dragonflyai.co',false,false,1200),
('brandwatch','Brandwatch AI','brandwatch','marketing','AI social listening tool for brand monitoring and consumer insights.','👁️','https://brandwatch.com',false,false,3600),
('sprout-social','Sprout Social AI','sprout','marketing','AI social media management with sentiment analysis and automation.','🌱','https://sproutsocial.com',false,false,4100),
('ghostwriter','Ghostwriter AI','ghostwriter','marketing','AI for PR and communications teams to draft press releases and pitches.','👻','https://ghostwriterai.com',false,false,800),
('copy-smith','Copysmith','copysmith','marketing','AI copywriting tool for e-commerce with bulk content generation.','🔨','https://copysmith.ai',false,false,1500),

-- ━━━ AUTOMATION & NO-CODE ━━━
('flowise','Flowise','flowise','automation','Open-source visual builder for creating LLM-powered AI agents and workflows.','🌊','https://flowiseai.com',true,false,3800),
('langchain','LangChain','langchain','automation','Framework for building LLM applications and AI agent workflows.','⛓️','https://langchain.com',true,false,6200),
('langflow','Langflow','langflow','automation','Low-code UI for building and deploying LangChain workflows visually.','🌀','https://langflow.org',true,false,2900),
('dify','Dify.ai','dify','automation','Open-source LLM app development platform with visual workflow builder.','🔧','https://dify.ai',true,false,3400),
('relevance-ai','Relevance AI','relevance','automation','No-code platform to build AI agents and automated workflows.','🔗','https://relevanceai.com',true,false,2500),
('bardeen','Bardeen AI','bardeen','automation','AI automation tool for browser actions — scraping, form filling, and workflows.','⚡','https://bardeen.ai',true,false,3200),
('taskade','Taskade AI','taskade','automation','AI project management and collaboration tool with built-in agents.','✅','https://taskade.com',true,false,3800),
('activepieces','ActivePieces','activepieces','automation','Open-source Zapier alternative with AI-powered automation blocks.','⚙️','https://activepieces.com',true,false,2100),
('rivet','Rivet','rivet','automation','Open-source visual AI programming environment for building LLM pipelines.','🔩','https://rivet.ironcladapp.com',true,false,1500),
('gumloop','Gumloop','gumloop','automation','No-code AI workflow builder for scraping, processing, and automating tasks.','🔄','https://gumloop.com',true,false,1900),
('pickaxe','Pickaxe','pickaxe','automation','No-code platform to build AI tools and workflows from a template.','⛏️','https://pickaxe.com',true,false,1200),
('latenode','Latenode','latenode','automation','Low-code AI automation platform with code capabilities when needed.','🚀','https://latenode.com',true,false,1600),
('pabbly','Pabbly Connect','pabbly','automation','Workflow automation tool connecting 1000+ apps with one-time pricing.','🔗','https://pabbly.com',false,false,3100),
('integrately','Integrately','integrately','automation','One-click automation platform with 8 million+ ready-made workflows.','⚡','https://integrately.com',true,false,2400),
('albato','Albato','albato','automation','No-code integration platform for connecting SaaS apps automatically.','🔄','https://albato.com',false,false,1100),
('workato','Workato','workato','automation','Enterprise automation platform with AI-powered workflow suggestions.','⚙️','https://workato.com',false,false,3800),
('parabola','Parabola','parabola','automation','No-code data transformation tool for automating spreadsheet workflows.','📊','https://parabola.io',false,false,1700),
('talend','Talend AI','talend','automation','Enterprise data integration platform with AI-powered quality checks.','🔷','https://talend.com',false,false,2200),
('cobalt','Cobalt','cobalt','automation','Embedded integration platform for SaaS products with AI connectors.','💠','https://cobalt.io',false,false,900),
('levity','Levity','levity','automation','No-code AI workflow tool for classifying emails, documents, and images.','🪶','https://levity.ai',false,false,1300),

-- ━━━ DESIGN & BRANDING ━━━
('looka','Looka','looka','design','AI-powered logo maker and brand identity generator for startups.','💎','https://looka.com',true,false,5400),
('brandmark','Brandmark.io','brandmark','design','AI logo designer with color palette and font pairing suggestions.','🎨','https://brandmark.io',false,false,2800),
('hatchful','Hatchful (Shopify)','hatchful','design','Free AI logo maker by Shopify for small businesses and entrepreneurs.','🐣','https://hatchful.shopify.com',true,false,3100),
('wix-ai','Wix ADI','wix-adi','design','AI website designer that builds complete websites from a questionnaire.','🌐','https://wix.com',true,false,6200),
('framer-ai','Framer AI','framer-ai','design','AI website builder integrated into Framer design tool for prototyping.','🖼️','https://framer.com',true,false,4800),
('webflow-ai','Webflow AI','webflow-ai','design','AI-assisted visual web design and CMS platform for professionals.','🌀','https://webflow.com',true,false,7100),
('uizard','Uizard','uizard','design','AI UI design tool to wireframe and prototype apps from sketches or text.','🎯','https://uizard.io',true,false,3400),
('galileo','Galileo AI','galileo','design','AI UI designer generating polished app screens from text descriptions.','🔭','https://usegalileo.ai',false,false,2100),
('relume','Relume','relume','design','AI website builder creating sitemaps and wireframes for Figma/Webflow.','🎨','https://relume.io',false,false,2800),
('visily','Visily AI','visily','design','AI wireframing and UI design tool with screenshot-to-design features.','✏️','https://visily.ai',true,false,2100),
('patterned','Patterned AI','patterned','design','AI pattern generator for seamless backgrounds and textile designs.','🔷','https://patterned.ai',true,false,1600),
('khroma','Khroma','khroma','design','AI color palette generator trained on designer-curated color combinations.','🌈','https://khroma.co',true,false,2400),
('colormind','Colormind','colormind','design','AI color scheme generator that learns from photos and artwork.','🎨','https://colormind.io',true,false,2100),
('stockai','Stock AI','stockai','design','AI stock photo generator producing royalty-free realistic images.','📸','https://stockai.com',true,false,1400),
('ilus','Ilus AI','ilus','design','AI illustration generator creating consistent character and scene art.','🎭','https://ilus.ai',false,false,1100),
('rendernet','RenderNet','rendernet','design','AI character consistency engine for generating stable human faces.','👤','https://rendernet.ai',true,false,1800),
('mokker','Mokker AI','mokker','design','AI product mockup generator placing your product in realistic scenes.','📦','https://mokker.ai',true,false,1600),
('hotpot-ai','Hotpot AI','hotpot','design','Collection of AI tools for image generation, editing, and upscaling.','🌶️','https://hotpot.ai',true,false,2900),
('profile-pic','ProfilePicture.ai','profilepic','design','AI professional headshot generator from casual selfies.','🤳','https://profilepicture.ai',false,false,2400),
('artbreeder','Artbreeder','artbreeder','design','AI art tool for creating portraits, landscapes, and abstract art by mixing images.','🌱','https://artbreeder.com',true,false,4100)

ON CONFLICT (id) DO NOTHING;
