-- SYNAP AI TOOLS — BATCH 7 (200 famous tools)
INSERT INTO public.ai_tools (id,name,slug,category_id,description,icon_emoji,website_url,has_free_tier,is_featured,click_count) VALUES

-- ━━━ DESIGN & UI/UX AI ━━━
('figma-ai','Figma AI','figma-ai','design','AI design features in Figma with auto-layout and prototyping.','🎨','https://figma.com',true,true,18000),
('framer','Framer','framer','design','AI website builder creating production-ready sites from prompts.','🔲','https://framer.com',true,true,8200),
('relume','Relume AI','relume','design','AI wireframe and sitemap generator for web designers.','🔷','https://relume.io',true,false,3400),
('uizard','Uizard','uizard','design','AI turning hand-drawn sketches into digital UI designs.','✏️','https://uizard.io',true,false,3800),
('galileo-ai','Galileo AI','galileo','design','AI UI design generator creating editable Figma designs from text.','🔭','https://usegalileo.ai',false,false,2600),
('diagram','Diagram (Figma)','diagram','design','AI design tools for Figma including Magician and Automator.','✨','https://diagram.com',true,false,3200),
('musho','Musho AI','musho','design','AI Figma plugin generating landing page designs from prompts.','🎨','https://musho.ai',true,false,1800),
('visily','Visily','visily','design','AI turning screenshots and text into editable wireframes.','📐','https://visily.ai',true,false,2200),
('builder-io','Builder.io AI','builder-io','design','AI converting Figma designs to production React and Vue code.','🏗️','https://builder.io',true,false,3600),
('anima-ai','Anima','anima','design','AI converting Figma and XD designs to developer-ready code.','🔷','https://animaapp.com',true,false,2400),
('spline-ai','Spline AI','spline','design','AI 3D design tool creating interactive 3D web experiences.','🔮','https://spline.design',true,false,4200),
('vectary','Vectary AI','vectary','design','AI 3D and AR design platform for product visualization.','🧊','https://vectary.com',true,false,2800),
('polotno','Polotno Studio','polotno','design','Free AI canvas design editor similar to Canva for developers.','🎨','https://studio.polotno.com',true,false,1600),
('designify','Designify','designify','design','AI photo design tool creating professional product photos.','🖼️','https://designify.com',true,false,2200),
('autodraw','AutoDraw','autodraw','design','Google AI drawing tool turning rough sketches into finished art.','✏️','https://autodraw.com',true,false,3400),
('brandbird','Brandbird','brandbird','design','AI screenshot beautifier for social media and marketing.','🐦','https://brandbird.app',true,false,1400),
('shots-so','Shots.so','shots','design','AI mockup generator creating beautiful device frames for screenshots.','📱','https://shots.so',true,false,2000),
('ray-so','Ray.so','ray','design','AI code screenshot tool creating beautiful code snippets.','🌊','https://ray.so',true,false,2800),
('carbon','Carbon','carbon','design','Open-source tool creating beautiful images of source code.','🌑','https://carbon.now.sh',true,false,3200),
('colorhunt','Color Hunt AI','colorhunt','design','AI curated color palette generator for designers.','🎨','https://colorhunt.co',true,false,2600),

-- ━━━ E-COMMERCE AI ━━━
('shopify-ai','Shopify Magic','shopify-ai','marketing','AI features in Shopify for product descriptions and chat.','🛒','https://shopify.com',false,true,12000),
('amazon-ai','Amazon Seller AI','amazon-ai','marketing','AI tools for Amazon sellers with listing optimization.','📦','https://sell.amazon.com',false,false,8400),
('sellesta','Sellesta AI','sellesta','marketing','AI Amazon listing optimizer improving keywords and conversion.','📈','https://sellesta.com',true,false,2200),
('quartile','Quartile AI','quartile','marketing','AI advertising platform optimizing Amazon and e-commerce ads.','📊','https://quartile.com',false,false,1800),
('prisync','Prisync AI','prisync','marketing','AI competitor price tracking and dynamic pricing for e-commerce.','💰','https://prisync.com',false,false,1600),
('nosto','Nosto AI','nosto','marketing','AI personalized shopping experiences for e-commerce sites.','🎯','https://nosto.com',false,false,2400),
('clerk-io','Clerk.io','clerk-io','marketing','AI search and product recommendations for online stores.','🔍','https://clerk.io',false,false,1800),
('algolia-ai','Algolia AI','algolia','marketing','AI search and discovery platform for e-commerce and apps.','🔎','https://algolia.com',true,false,4200),
('bloomreach','Bloomreach AI','bloomreach','marketing','AI commerce experience platform with search and merchandising.','🌸','https://bloomreach.com',false,false,2600),
('dynamic-yield','Dynamic Yield','dynamic-yield','marketing','AI personalization platform for e-commerce by Mastercard.','🎯','https://dynamicyield.com',false,false,2200),

-- ━━━ AUTOMATION & WORKFLOW AI ━━━
('zapier-ai','Zapier AI','zapier','automation','AI workflow automation connecting 6000+ apps with natural language.','⚡','https://zapier.com',true,true,16000),
('make-ai','Make (Integromat)','make','automation','Visual AI workflow automation builder with 1500+ app integrations.','🔄','https://make.com',true,true,9800),
('n8n','n8n','n8n','automation','Open-source AI workflow automation with self-hosting option.','🔗','https://n8n.io',true,false,5200),
('ifttt-ai','IFTTT AI','ifttt','automation','AI automation connecting smart devices and apps with if-then logic.','🔌','https://ifttt.com',true,false,6400),
('bardeen','Bardeen AI','bardeen','automation','AI browser automation for repetitive tasks without coding.','🤖','https://bardeen.ai',true,false,3200),
('pipedream','Pipedream','pipedream','automation','Developer-first AI workflow automation with code and no-code.','🔷','https://pipedream.com',true,false,3800),
('activepieces','Activepieces','activepieces','automation','Open-source AI automation alternative to Zapier with self-hosting.','🧩','https://activepieces.com',true,false,2200),
('tray-io','Tray.io','tray','automation','Enterprise AI automation platform with general purpose integration.','🔷','https://tray.io',false,false,2600),
('workato','Workato','workato','automation','Enterprise AI automation with recipes for complex workflows.','🔧','https://workato.com',false,false,3200),
('power-automate','Power Automate AI','power-automate','automation','Microsoft AI workflow automation with desktop and cloud flows.','⚡','https://powerautomate.microsoft.com',true,false,7200),
('uipath-ai','UiPath AI','uipath','automation','Enterprise AI robotic process automation for business workflows.','🤖','https://uipath.com',true,false,5800),
('automation-anywhere','Automation Anywhere','aa','automation','Enterprise AI-powered RPA with intelligent automation.','🔷','https://automationanywhere.com',false,false,4200),
('browse-ai','Browse AI','browse-ai','automation','AI web scraping and monitoring tool without coding.','🌐','https://browse.ai',true,false,2800),
('apify','Apify','apify','automation','AI web scraping and automation platform with ready-made actors.','🕷️','https://apify.com',true,false,3400),
('phantom-buster','PhantomBuster','phantombuster','automation','AI lead generation with LinkedIn and social media automation.','👻','https://phantombuster.com',false,false,3600),
('clay-ai','Clay','clay','automation','AI data enrichment and outreach platform for GTM teams.','🏺','https://clay.com',false,false,2800),
('relevance-ai','Relevance AI','relevance','automation','AI agent builder creating custom AI tools and workflows.','🔷','https://relevanceai.com',true,false,1800),
('stack-ai','Stack AI','stack-ai','automation','No-code AI workflow builder with LLM integration for enterprises.','📚','https://stack-ai.com',true,false,1600),
('respell','Respell','respell','automation','AI workflow builder creating agents that complete complex tasks.','✨','https://respell.ai',true,false,1400),
('lindy-ai','Lindy AI','lindy','automation','AI assistant builder creating custom AI employees for any task.','🤖','https://lindy.ai',true,false,2200),

-- ━━━ DATA & ANALYTICS AI ━━━
('tableau-ai','Tableau AI','tableau','research','AI analytics and visualization platform by Salesforce.','📊','https://tableau.com',false,true,8200),
('power-bi-ai','Power BI AI','power-bi','research','Microsoft AI business intelligence with natural language queries.','📊','https://powerbi.microsoft.com',true,true,9600),
('thoughtspot','ThoughtSpot','thoughtspot','research','AI analytics platform with natural language search for data.','🔍','https://thoughtspot.com',false,false,3200),
('hex-ai','Hex AI','hex','research','AI collaborative data workspace with SQL, Python, and notebooks.','🔷','https://hex.tech',true,false,2800),
('databricks-ai','Databricks AI','databricks','research','AI lakehouse platform for data engineering and ML at scale.','🔷','https://databricks.com',false,false,5800),
('dataiku','Dataiku','dataiku','research','Enterprise AI platform for data science and ML lifecycle.','🔬','https://dataiku.com',false,false,3600),
('obviously-ai','Obviously AI','obviously','research','No-code AI predictions building ML models in minutes.','🔮','https://obviously.ai',true,false,1800),
('akkio','Akkio','akkio','research','No-code AI platform for predictive analytics and data analysis.','📈','https://akkio.com',true,false,2200),
('polymer','Polymer AI','polymer','research','AI turning spreadsheets into interactive dashboards instantly.','🔷','https://polymersearch.com',true,false,1600),
('rows-ai','Rows AI','rows','research','AI spreadsheet with built-in data analysis and integrations.','📊','https://rows.com',true,false,2400),
('equals-ai','Equals AI','equals','research','AI-native spreadsheet for startups with SQL and charts.','📈','https://equals.com',false,false,1400),
('quadratic','Quadratic','quadratic','research','AI spreadsheet with Python, SQL, and formulas in one tool.','📊','https://quadratichq.com',true,false,1200),
('baseten','Baseten','baseten','research','AI inference platform deploying ML models with auto-scaling.','🔷','https://baseten.co',true,false,2000),
('banana-dev','Banana.dev','banana','research','Serverless GPU platform for deploying ML models as APIs.','🍌','https://banana.dev',true,false,1600),

-- ━━━ CUSTOMER SUPPORT AI ━━━
('intercom-ai','Intercom Fin','intercom','chat','AI customer service chatbot resolving 50% of queries instantly.','💬','https://intercom.com',false,true,8400),
('zendesk-ai','Zendesk AI','zendesk','chat','AI customer service platform with intelligent triage and bots.','🟢','https://zendesk.com',false,true,7800),
('tidio-ai','Tidio AI','tidio','chat','AI chatbot for e-commerce with live chat and Lyro AI.','💬','https://tidio.com',true,false,4200),
('freshdesk-ai','Freshdesk AI','freshdesk','chat','AI helpdesk with Freddy AI for ticket routing and resolution.','💧','https://freshdesk.com',true,false,3800),
('drift-ai','Drift AI','drift','chat','AI conversational marketing platform for B2B sales.','💬','https://drift.com',false,false,3200),
('chatbase','Chatbase','chatbase','chat','AI chatbot builder trained on your data for customer support.','🤖','https://chatbase.co',true,false,5600),
('botpress','Botpress','botpress','chat','Open-source AI chatbot builder with visual flow editor.','🤖','https://botpress.com',true,false,3800),
('voiceflow','Voiceflow','voiceflow','chat','AI conversation design platform for chatbots and voice apps.','🔷','https://voiceflow.com',true,false,3200),
('ada-cx','Ada CX','ada-cx','chat','AI customer service automation resolving inquiries at scale.','🤖','https://ada.cx',false,false,2800),
('forethought','Forethought','forethought','chat','AI customer support with predictive ticket routing and resolution.','🔮','https://forethought.ai',false,false,2200),

-- ━━━ LEGAL & COMPLIANCE AI ━━━
('harvey-ai','Harvey AI','harvey','research','AI legal assistant for research, drafting, and contract analysis.','⚖️','https://harvey.ai',false,false,4200),
('casetext','CaseText (Thomson Reuters)','casetext','research','AI legal research with CoCounsel GPT-4 powered assistant.','📚','https://casetext.com',false,false,3600),
('lexis-ai','Lexis+ AI','lexis','research','LexisNexis AI legal research and drafting assistant.','📖','https://lexisnexis.com',false,false,3200),
('ironclad','Ironclad AI','ironclad','research','AI contract lifecycle management with smart clause suggestions.','📄','https://ironcladapp.com',false,false,2800),
('docusign-ai','DocuSign IAM','docusign','research','AI agreement management with intelligent contract analysis.','✍️','https://docusign.com',false,false,5200),
('spellbook','Spellbook','spellbook','research','AI contract drafting assistant reviewing and suggesting clauses.','📜','https://spellbook.legal',false,false,2400),
('latch-ai','Latch AI','latch','research','AI contract review tool analyzing agreements for risks instantly.','🔒','https://latch.legal',true,false,1600),
('lawgeex','LawGeex','lawgeex','research','AI contract review platform automating legal approvals.','⚖️','https://lawgeex.com',false,false,2000),
('luminance','Luminance AI','luminance','research','AI legal technology for contract negotiation and due diligence.','💡','https://luminance.com',false,false,2600),
('lexion','Lexion AI','lexion','research','AI contract management platform organizing and tracking agreements.','📋','https://lexion.ai',false,false,1400),

-- ━━━ HR & RECRUITMENT AI ━━━
('linkedin-recruiter','LinkedIn Recruiter AI','linkedin-recruiter','research','AI-powered talent sourcing with smart matching on LinkedIn.','💼','https://linkedin.com/talent',false,false,8200),
('hirevue','HireVue AI','hirevue','research','AI video interview platform with candidate assessment analytics.','🎥','https://hirevue.com',false,false,3600),
('textio','Textio','textio','research','AI augmented writing for job posts and performance feedback.','📝','https://textio.com',false,false,2400),
('beamery','Beamery AI','beamery','research','AI talent lifecycle management with CRM and workforce planning.','🔷','https://beamery.com',false,false,2000),
('eightfold','Eightfold AI','eightfold','research','AI talent intelligence platform matching candidates to roles.','🔷','https://eightfold.ai',false,false,2800),
('phenom','Phenom AI','phenom','research','AI talent experience platform for hiring, development, retention.','🔷','https://phenom.com',false,false,2200),
('paradox-ai','Paradox AI','paradox','research','AI recruiting assistant Olivia automating hiring conversations.','💬','https://paradox.ai',false,false,2600),
('fetcher','Fetcher AI','fetcher','research','AI recruiting tool automating candidate sourcing and outreach.','🎯','https://fetcher.ai',false,false,1600),
('manatal','Manatal AI','manatal','research','AI recruitment software with candidate scoring and enrichment.','🔷','https://manatal.com',true,false,1800),
('dover-ai','Dover','dover','research','AI recruiting platform automating end-to-end hiring pipeline.','🔷','https://dover.com',true,false,1400)

ON CONFLICT (id) DO NOTHING;
