-- SYNAP AI TOOLS — BATCH 3 (200 tools)
-- Run this in Supabase SQL Editor AFTER Batch 1 & 2
INSERT INTO public.ai_tools (id,name,slug,category_id,description,icon_emoji,website_url,has_free_tier,is_featured,click_count) VALUES

-- ━━━ MORE WRITING TOOLS ━━━
('compose-ai','Compose AI','compose-ai','writing','Chrome extension for AI autocomplete and text generation anywhere online.','⌨️','https://compose.ai',true,false,3200),
('textblaze','Text Blaze','textblaze','writing','AI text expander that inserts smart snippets and templates anywhere.','⚡','https://blaze.today',true,false,2800),
('flowrite','Flowrite','flowrite','writing','AI email and message writer that turns instructions into ready-to-send text.','✉️','https://flowrite.com',false,false,2100),
('mailr','Mailr','mailr','writing','AI email writer that drafts professional replies in seconds.','📧','https://mailr.ai',true,false,1200),
('smartwriter','SmartWriter AI','smartwriter','writing','AI cold email personalization tool for B2B outreach campaigns.','✍️','https://smartwriter.ai',false,false,1900),
('lavender','Lavender','lavender','writing','AI email coach that scores and improves cold outreach in real-time.','💜','https://lavender.ai',true,false,2400),
('regie-ai','Regie.ai','regie','writing','AI sales content platform for generating prospecting emails and sequences.','🎯','https://regie.ai',false,false,1600),
('tailwind-ai','Tailwind AI','tailwind-ai','writing','AI social media caption and content writer for Instagram and Pinterest.','📝','https://tailwindapp.com',false,false,2200),
('contentshake','ContentShake AI','contentshake','writing','Semrush AI writing tool for creating SEO-optimized articles fast.','🥤','https://semrush.com/contentshake',false,false,1800),
('blogify','Blogify','blogify','writing','AI that converts YouTube videos and podcasts into blog posts automatically.','📰','https://blogify.ai',true,false,1400),
('katteb','Katteb','katteb','writing','AI fact-checked content writer sourcing from trusted web references.','📰','https://katteb.com',false,false,1100),
('ai-writer','AI-Writer','ai-writer','writing','AI article generator with source citations and verifiable text outputs.','📝','https://ai-writer.com',false,false,1700),
('closerscopy','ClosersCopy','closerscopy','writing','AI copywriting tool with 700+ templates and custom AI workflow builder.','📋','https://closerscopy.com',false,false,1500),
('describely','Describely','describely','writing','AI product description generator for e-commerce and Amazon sellers.','🛍️','https://describely.ai',false,false,1100),
('ocoya','Ocoya','ocoya','writing','AI social media content creator with scheduling and analytics built in.','🌊','https://ocoya.com',false,false,1800),
('simplified','Simplified','simplified','writing','All-in-one AI design and content creation platform for marketing teams.','✅','https://simplified.com',true,false,3400),
('writier','Writier','writier','writing','AI writing assistant focused on generating long-form blog content.','🖊️','https://writier.io',true,false,900),
('scalenut','Scalenut','scalenut','writing','AI content platform for SEO research, writing, and optimization.','📊','https://scalenut.com',false,false,2100),
('autoblogging','Autoblogging AI','autoblogging','writing','AI bulk article writer for generating hundreds of SEO posts quickly.','🤖','https://autoblogging.ai',false,false,1300),
('ahrefs-ai','Ahrefs AI','ahrefs-ai','writing','AI writing tools integrated into Ahrefs SEO platform for content creation.','🔍','https://ahrefs.com',false,false,5400),

-- ━━━ MORE AUTOMATION & AGENTS ━━━
('autogpt','AutoGPT','autogpt','automation','Open-source autonomous AI agent that completes multi-step tasks independently.','🤖','https://agpt.co',true,true,9800),
('agentgpt','AgentGPT','agentgpt','automation','Browser-based autonomous AI agent that creates and runs goal-oriented tasks.','🌐','https://agentgpt.reworkd.ai',true,false,4200),
('superagent','SuperAgent','superagent','automation','Open-source framework for building production-ready AI agents and assistants.','🦸','https://superagent.sh',true,false,2100),
('crew-ai','CrewAI','crewai','automation','Framework for orchestrating multiple AI agents working together as a team.','👥','https://crewai.com',true,false,3800),
('autogen','AutoGen (Microsoft)','autogen','automation','Microsoft''s framework for building multi-agent AI conversation systems.','🔄','https://microsoft.github.io/autogen',true,false,3200),
('semantic-kernel','Semantic Kernel','semantic-kernel','automation','Microsoft SDK for integrating AI models into .NET and Python applications.','🔷','https://github.com/microsoft/semantic-kernel',true,false,2400),
('haystack','Haystack','haystack','automation','Open-source framework for building NLP pipelines and RAG applications.','🔍','https://haystack.deepset.ai',true,false,2800),
('llamaindex','LlamaIndex','llamaindex','automation','Data framework for connecting LLMs with external data sources and APIs.','🦙','https://llamaindex.ai',true,false,3600),
('phidata','Phidata','phidata','automation','Platform for building AI assistants with memory, knowledge, and tools.','🔧','https://phidata.com',true,false,1900),
('mem0','Mem0','mem0','automation','Memory layer for AI agents providing persistent, personalized memory.','🧠','https://mem0.ai',true,false,2100),
('multion','MultiOn','multion','automation','AI agent that browses the web and completes tasks on your behalf.','🌐','https://multion.ai',false,false,2800),
('adept-ai','Adept AI','adept','automation','AI agent that takes actions on any software using natural language commands.','🤖','https://adept.ai',false,false,2400),
('oscopilot','OS-Copilot','oscopilot','automation','AI agent for automating operating system tasks through natural language.','🖥️','https://os-copilot.github.io',true,false,1100),
('axiom-ai','Axiom.ai','axiom','automation','No-code browser automation platform using AI for web scraping and tasks.','⚡','https://axiom.ai',true,false,1800),
('browse-ai','Browse AI','browse-ai','automation','No-code AI tool for scraping and monitoring websites without coding.','🌐','https://browse.ai',true,false,2600),
('clay','Clay','clay','automation','AI-powered data enrichment and sales prospecting automation platform.','🏺','https://clay.com',false,false,3100),
('phantombuster','PhantomBuster AI','phantombuster','automation','AI cloud automation platform for LinkedIn, Instagram, and web scraping.','👻','https://phantombuster.com',true,false,2900),
('magical','Magical AI','magical','automation','AI automation tool for automating repetitive browser tasks and data entry.','✨','https://getmagical.com',true,false,2200),
('ifttt-ai','IFTTT AI','ifttt','automation','AI-enhanced platform connecting 900+ apps with if-this-then-that automations.','🔗','https://ifttt.com',true,false,4900),
('tray-io','Tray.io AI','tray','automation','Enterprise automation platform with AI-powered workflow suggestions.','🔧','https://tray.io',false,false,2100),

-- ━━━ MORE DESIGN TOOLS ━━━
('adobe-express','Adobe Express AI','adobe-express','design','AI-powered quick design tool for social media, flyers, and web graphics.','🎨','https://express.adobe.com',true,false,7200),
('snappa','Snappa AI','snappa','design','AI graphic design tool for creating social media graphics and ads.','📐','https://snappa.com',true,false,2800),
('crello','VistaCreate AI','vistacreatee','design','AI graphic design platform with animated templates for social content.','🎭','https://create.vista.com',true,false,2400),
('pixlr','Pixlr AI','pixlr','design','AI-powered online photo editor with background removal and enhancement tools.','🖼️','https://pixlr.com',true,false,4600),
('picsart-ai','PicsArt AI','picsart','design','AI photo editor with background changer, filters, and art style tools.','🎨','https://picsart.com',true,false,7800),
('befunky','BeFunky AI','befunky','design','AI photo editor and collage maker for quick creative projects.','🎪','https://befunky.com',true,false,3200),
('designify','Designify','designify','design','AI tool that removes backgrounds and creates professional product photos.','✂️','https://designify.com',true,false,2100),
('unscreen','Unscreen','unscreen','design','AI tool for removing video backgrounds with one click.','📹','https://unscreen.com',true,false,2800),
('bg-eraser','BGEraser','bgeraser','design','AI background eraser for product photos and portrait images.','🧹','https://bgeraser.com',true,false,1600),
('colorize','Palette.fm','palette','design','AI photo colorizer that adds realistic colors to black and white images.','🌈','https://palette.fm',true,false,2200),
('vectorizer-ai','Vectorizer.ai','vectorizer','design','AI tool that converts raster images to SVG vector format automatically.','↔️','https://vectorizer.ai',true,false,1900),
('icons8-ai','Icons8 AI','icons8','design','AI icon generator and consistency-matching icon library with editing tools.','🔷','https://icons8.com',true,false,3600),
('logoai','LogoAI','logoai','design','AI logo maker with branding kit including business cards and social posts.','💎','https://logoai.com',true,false,2400),
('tailor-brands','Tailor Brands AI','tailor','design','AI branding platform for creating logos, websites, and business identity.','✂️','https://tailorbrands.com',false,false,3100),
('namelix','Namelix','namelix','design','AI business name generator with domain availability checker.','🏷️','https://namelix.com',true,false,3800),
('namelix-logo','Logomaster.ai','logomaster','design','AI logo creator with color psychology and style matching.','🎨','https://logomaster.ai',false,false,1700),
('typedream','Typedream AI','typedream','design','AI website builder with GPT-4 content generation and no-code design.','💬','https://typedream.com',false,false,1400),
('carrd','Carrd AI','carrd','design','Simple one-page website builder with AI content suggestions.','🃏','https://carrd.co',true,false,3200),
('zysite','Zyrosite AI','zyro-site','design','AI website builder by Hostinger with integrated content generation.','⚡','https://zyro.com',false,false,2100),
('mixo','Mixo AI','mixo','design','AI startup website generator creating landing pages in seconds.','🎨','https://mixo.io',true,false,2600),

-- ━━━ MORE VIDEO TOOLS ━━━
('vidu','Vidu AI','vidu','video','Chinese AI video generator by Tsinghua University with cinematic quality.','🎬','https://vidu.com',true,false,3400),
('gen3','Runway Gen-3 Alpha','gen3','video','Runway''s latest AI video generation model for cinematic quality clips.','🎥','https://runwayml.com',false,true,8900),
('minimax-video','MiniMax Video','minimax','video','Chinese AI video generator with industry-leading motion quality.','🎞️','https://minimaxi.com',false,false,2800),
('cogvideo','CogVideo','cogvideo','video','Open-source text-to-video model from Tsinghua University for research.','🎬','https://github.com/THUDM/CogVideo',true,false,1800),
('zeroscope','Zeroscope','zeroscope','video','Open-source text-to-video Stable Diffusion model for short clips.','🎥','https://zeroscope.replicate.dev',true,false,1500),
('hourone-video','HourOne','hourone','video','AI video platform creating human avatar videos for enterprise use.','⏰','https://hourone.ai',false,false,2100),
('powtoon','Powtoon AI','powtoon','video','AI animated video maker for explainer videos and presentations.','🎭','https://powtoon.com',true,false,3600),
('animoto','Animoto AI','animoto','video','AI-powered video maker for slideshows and marketing videos.','🎬','https://animoto.com',true,false,2900),
('biteable','Biteable AI','biteable','video','AI video maker for creating quick studio-quality videos and ads.','🎥','https://biteable.com',true,false,2200),
('kapwing-ai','Kapwing AI','kapwing','video','AI video editor for removing silences, adding captions, and resizing clips.','✂️','https://kapwing.com',true,false,4100),
('cliptv','Clip.tv AI','cliptv','video','AI video clipping tool that finds viral moments in long videos.','✂️','https://clip.tv',true,false,1800),
('munch','Munch','munch','video','AI video repurposing tool extracting engaging clips for social media.','🍔','https://getmunch.com',true,false,2400),
('wisecut','Wisecut','wisecut','video','AI video editor that auto-cuts silences and adds background music.','✂️','https://wisecut.video',true,false,1900),
('lenvideo','Lenvideo AI','lenvideo','video','AI talking head video creator from text with realistic avatars.','🎤','https://lenvideo.ai',false,false,1100),
('rask-ai','Rask AI','rask-ai','video','AI video dubbing and localization into 130+ languages with lip sync.','🌍','https://rask.ai',false,false,2600),
('papercup','Papercup','papercup','video','AI dubbing platform cloning voice for natural-sounding video translation.','☕','https://papercup.com',false,false,1500),
('d-id','D-ID','d-id','video','AI talking avatar creator for training, marketing, and creative videos.','👤','https://d-id.com',true,false,4800),
('studio-d-id','D-ID Creative Reality Studio','d-id-studio','video','AI digital human platform creating photorealistic talking video avatars.','🎭','https://studio.d-id.com',true,false,3200),
('vmake','VMake AI','vmake','video','AI video enhancer and creator with product video generation features.','🎬','https://vmake.ai',true,false,1600),
('topaz-video','Topaz Video AI','topaz-video','video','AI video enhancer for upscaling, denoising, and motion restoration.','🔍','https://topazlabs.com/video-ai',false,false,3400),

-- ━━━ MORE AUDIO TOOLS ━━━
('lalal-ai','LALAL.AI','lalal','audio','AI stem splitter separating vocals, instruments, and drums from songs.','🎵','https://lalal.ai',true,false,4200),
('moises','Moises App','moises','audio','AI music tool for separating stems, key detection, and chord recognition.','🎶','https://moises.ai',true,false,3600),
('splitter-ai','Splitter.ai','splitter','audio','AI vocal remover and music stem splitter for DJ and music production.','🎛️','https://splitter.ai',true,false,2800),
('vocalize','Vocalize.ai','vocalize','audio','AI voice cloning and text-to-speech platform for content creators.','🎤','https://vocalize.ai',false,false,1400),
('wellsaid','WellSaid Labs','wellsaid','audio','AI voice studio creating natural-sounding human voiceovers for media.','🔊','https://wellsaidlabs.com',false,false,2100),
('lovo','LOVO AI','lovo','audio','AI voiceover generator with 500+ voices in 100+ languages for creators.','🎙️','https://lovo.ai',true,false,2900),
('listnr','Listnr','listnr','audio','AI text-to-speech tool and podcast hosting platform for creators.','🎧','https://listnr.ai',true,false,1800),
('play-ht','Play.ht','play-ht','audio','AI voice generator with ultra-realistic text-to-speech in 900+ voices.','▶️','https://play.ht',true,false,3400),
('voice-maker','VoiceMaker','voicemaker','audio','AI text-to-speech platform with 1000+ voices across 90+ languages.','🔈','https://voicemaker.in',true,false,2200),
('sounds-ai','Sounds.ai','sounds-ai','audio','AI audio tool for music generation, sound effects, and mixing.','🎵','https://sounds.ai',true,false,1100),
('audo-ai','Audo AI','audo','audio','AI audio cleanup tool removing noise from recordings automatically.','🔇','https://audo.ai',true,false,1600),
('accusonus','Accusonus AI','accusonus','audio','AI audio repair toolkit for removing noise, reverb, and distortion.','🔧','https://accusonus.com',false,false,1800),
('sonix','Sonix AI','sonix','audio','AI audio transcription and translation service in 40+ languages.','📝','https://sonix.ai',true,false,2700),
('trint','Trint','trint','audio','AI transcription platform for journalists and media teams globally.','📰','https://trint.com',false,false,2100),
('notta','Notta','notta','audio','AI meeting transcription and note-taking with 58-language support.','📋','https://notta.ai',true,false,3200),
('tactiq','Tactiq','tactiq','audio','AI meeting transcription Chrome extension for Google Meet and Zoom.','💬','https://tactiq.io',true,false,2400),
('airgram','Airgram','airgram','audio','AI meeting assistant for recording, transcribing, and sharing notes.','✈️','https://airgram.io',true,false,1900),
('sembly','Sembly AI','sembly','audio','AI meeting intelligence platform with automated action item tracking.','💡','https://sembly.ai',true,false,1700),
('jamie-ai','Jamie AI','jamie','audio','AI meeting assistant that auto-summarizes calls without joining them.','📝','https://meetjamie.ai',false,false,1400),
('fathom','Fathom AI','fathom','audio','Free AI meeting recorder and summarizer for Zoom and Google Meet.','🐋','https://fathom.video',true,true,6200),

-- ━━━ MORE RESEARCH & PRODUCTIVITY ━━━
('taskade-ai','Taskade','taskade-ai','research','AI workspace combining tasks, notes, docs, and real-time collaboration.','✅','https://taskade.com',true,false,3600),
('heights-platform','Heights Platform','heights','research','AI online course creator and community platform for knowledge creators.','⛰️','https://heightsplatform.com',false,false,1200),
('napkin-ai','Napkin AI','napkin','research','AI tool that converts text into infographics, diagrams, and visuals.','📝','https://napkin.ai',true,false,2800),
('beautiful-ai','Beautiful.ai','beautiful-ai','research','AI presentation maker with smart slide design and auto-formatting.','✨','https://beautiful.ai',false,false,3600),
('slideai','SlideAI','slideai','research','AI that generates PowerPoint presentations from text prompts instantly.','📊','https://slideai.co',true,false,2100),
('gamma-app','Gamma App','gamma','research','AI presentation, doc, and webpage creator from outline or paste.','🔷','https://gamma.app',true,true,7800),
('gamma-app','Gamma App','gamma','research','AI presentation, doc, and webpage creator from prompts and outlines.','🔷','https://gamma.app',true,false,4200),
('decktopus-ai','Decktopus AI','decktopus','research','AI presentation generator creating full decks from topic descriptions.','📊','https://decktopus.com',true,false,2400),
('prezi-ai','Prezi AI','prezi','research','AI-enhanced presentation tool with non-linear zoomable slides.','🔄','https://prezi.com',true,false,3800),
('pitch-ai','Pitch AI','pitch','research','AI collaborative presentation platform for startup decks and portfolios.','⚾','https://pitch.com',true,false,2900),
('deckrobot','DeckRobot','deckrobot','research','AI PowerPoint add-in for instant slide formatting and design.','🤖','https://deckrobot.com',false,false,1100),
('mindmup','MindMup AI','mindmup','research','AI mind mapping tool for brainstorming and project planning.','🧠','https://mindmup.com',true,false,2200),
('whimsical-ai','Whimsical AI','whimsical','research','AI flowchart and mind map maker with GPT-powered content generation.','🌀','https://whimsical.com',true,false,3100),
('miro-ai','Miro AI','miro','research','AI features in the popular online whiteboard for team collaboration.','⬜','https://miro.com',true,false,8900),
('figjam-ai','FigJam AI','figjam','research','AI collaborative whiteboard tool integrated in Figma for teams.','🎨','https://figma.com/figjam',true,false,5600),
('lucidchart-ai','Lucidchart AI','lucidchart','research','AI diagram maker for flowcharts, org charts, and process mapping.','📊','https://lucidchart.com',true,false,4800),
('diagrams-ai','Diagrams.net AI','diagrams-net','research','Free open-source diagramming tool with AI diagram generation.','📐','https://diagrams.net',true,false,3400),
('cloudcraft','Cloudcraft AI','cloudcraft','research','AI AWS architecture diagram builder for cloud infrastructure planning.','☁️','https://cloudcraft.co',false,false,2100),
('eraser-io','Eraser.io AI','eraser','research','AI technical diagram and documentation tool for engineering teams.','✏️','https://eraser.io',true,false,1800),
('kreado','Kreado AI','kreado','research','AI digital human video and content creation platform for marketing.','🎭','https://kreado.ai',false,false,1600),

-- ━━━ MORE MARKETING & SEO ━━━
('semrush-ai','Semrush AI','semrush-ai','marketing','Industry-leading SEO platform with AI writing assistant and keyword research.','🔍','https://semrush.com',false,true,12000),
('ahrefs','Ahrefs','ahrefs','marketing','Comprehensive SEO toolset with AI features for backlink analysis and research.','🔗','https://ahrefs.com',false,true,11000),
('moz-ai','Moz AI','moz','marketing','SEO software with AI-powered keyword research and site audit tools.','🟢','https://moz.com',true,false,5800),
('ubersuggest','Ubersuggest AI','ubersuggest','marketing','Neil Patel''s AI SEO and keyword research tool for small businesses.','🚀','https://ubersuggest.com',true,false,5200),
('kwfinder','KWFinder','kwfinder','marketing','AI keyword research tool finding low-difficulty keywords for SEO.','🔍','https://kwfinder.com',false,false,3400),
('answerthepublic','AnswerThePublic AI','answerthepublic','marketing','AI keyword and question research tool showing what people search for.','👥','https://answerthepublic.com',true,false,4600),
('explodingthopics','Exploding Topics','exploding-topics','marketing','AI tool discovering fast-growing topics before they trend mainstream.','📈','https://explodingtopics.com',true,false,3100),
('growthnotes','GrowthNotes AI','growthnotes','marketing','AI growth hacking newsletter with trend analysis and insights.','📊','https://growthnotes.co',true,false,900),
('coschedule','CoSchedule AI','coschedule','marketing','AI marketing calendar and headline analyzer for content planning.','📅','https://coschedule.com',false,false,2800),
('plannable','Plannable AI','plannable','marketing','AI social media planning and approval workflow tool for agencies.','📋','https://plannable.io',false,false,2100),
('later','Later AI','later','marketing','AI social media scheduling and visual planning tool for Instagram.','⏰','https://later.com',true,false,3800),
('missinglettr','MissingLettr','missinglettr','marketing','AI social media drip campaign creator from blog posts and articles.','✉️','https://missinglettr.com',false,false,1400),
('flick-ai','Flick AI','flick','marketing','AI social media assistant for hashtag research and content creation.','⚡','https://flick.social',false,false,1900),
('post-planner','Post Planner AI','postplanner','marketing','AI social media tool forecasting viral content for scheduling.','📅','https://postplanner.com',false,false,1600),
('oneup','OneUp AI','oneup','marketing','AI social media scheduler with Google Business and GMB posting support.','☝️','https://oneupapp.io',false,false,1100),
('mention','Mention AI','mention','marketing','AI media monitoring tool tracking brand mentions across the web.','👂','https://mention.com',false,false,2200),
('talkwalker','Talkwalker AI','talkwalker','marketing','AI social listening and analytics platform for global brands.','🔉','https://talkwalker.com',false,false,2600),
('audiense','Audiense AI','audiense','marketing','AI audience intelligence platform for Twitter and social segmentation.','👥','https://audiense.com',false,false,1800),
('phlanx','Phlanx','phlanx','marketing','AI influencer marketing platform with engagement rate calculator.','📊','https://phlanx.com',true,false,1400),
('upfluence','Upfluence AI','upfluence','marketing','AI-powered influencer search and campaign management platform.','📣','https://upfluence.com',false,false,2400),

-- ━━━ LANGUAGE & TRANSLATION ━━━
('deepl','DeepL','deepl','chat','AI translation tool outperforming Google Translate in accuracy and naturalness.','🌍','https://deepl.com',true,true,14000),
('google-translate-ai','Google Translate AI','google-translate','chat','World''s most-used AI translation service supporting 133+ languages.','🌐','https://translate.google.com',true,true,22000),
('reverso','Reverso AI','reverso','chat','AI translation and language learning tool with contextual examples.','🔄','https://reverso.net',true,false,5800),
('languagetool','LanguageTool','languagetool','writing','Open-source AI grammar and style checker for 25+ languages.','✅','https://languagetool.org',true,false,5200),
('prowritingaid','ProWritingAid','prowritingaid','writing','AI writing coach with 25+ in-depth writing style reports.','📊','https://prowritingaid.com',true,false,4600),
('ginger-ai','Ginger AI','ginger','writing','AI grammar checker and text rephraser with sentence rephrasing.','🍊','https://gingersoftware.com',true,false,2800),
('whitesmoke','WhiteSmoke AI','whitesmoke','writing','AI writing tool for grammar checking, translation, and style improvement.','💨','https://whitesmoke.com',false,false,2100),
('trinka-ai','Trinka AI','trinka','writing','AI grammar and language enhancement tool for academic writing.','✍️','https://trinka.ai',true,false,1800),
('scribbr','Scribbr AI','scribbr','writing','AI plagiarism checker and citation generator for academic papers.','📚','https://scribbr.com',false,false,3600),
('turnitin-ai','Turnitin AI','turnitin','writing','AI plagiarism detection and AI writing detection tool for education.','🔍','https://turnitin.com',false,false,4200),
('copyleaks','Copyleaks AI','copyleaks','writing','AI plagiarism detector supporting code, academic, and web content.','🔍','https://copyleaks.com',true,false,2900),
('originality-ai','Originality.ai','originality','writing','AI content detector identifying GPT-4 and AI-generated text accurately.','🔎','https://originality.ai',false,false,2400),
('gptzero','GPTZero','gptzero','writing','AI detection tool identifying ChatGPT and AI-written content in documents.','🤖','https://gptzero.me',true,false,3800),
('zerogpt','ZeroGPT','zerogpt','writing','Free AI text detector identifying ChatGPT and AI-generated paragraphs.','🔬','https://zerogpt.com',true,false,2600),
('sapling-ai','Sapling AI','sapling','writing','AI writing assistant for customer service teams with response suggestions.','🌿','https://sapling.ai',true,false,1800),
('textmetrics','Textmetrics','textmetrics','writing','AI content optimization platform for inclusive and high-performing text.','📊','https://textmetrics.com',false,false,1200),
('acrolinx','Acrolinx AI','acrolinx','writing','Enterprise AI content governance platform for consistent brand writing.','🎯','https://acrolinx.com',false,false,1600),
('writer-com','Writer','writer-com','writing','Enterprise AI writing platform with brand voice training and compliance.','✍️','https://writer.com',false,false,2400),
('copygenius','CopyGenius','copygenius','writing','AI copywriting tool for ads, product descriptions, and landing pages.','💡','https://copygenius.io',true,false,1100),
('writecream','Writecream','writecream','writing','AI content generator for cold emails, ads, articles, and audio icebreakers.','🍦','https://writecream.com',true,false,1700)

ON CONFLICT (id) DO NOTHING;
