-- SYNAP AI TOOLS — BATCH 4 (200 tools)
-- Run this in Supabase SQL Editor AFTER Batch 1, 2 & 3
INSERT INTO public.ai_tools (id,name,slug,category_id,description,icon_emoji,website_url,has_free_tier,is_featured,click_count) VALUES

-- ━━━ GAMING & ENTERTAINMENT AI ━━━
('inworld-ai','Inworld AI','inworld','chat','AI character engine for creating dynamic NPCs in games with real personality.','🎮','https://inworld.ai',true,false,3800),
('convai','Convai','convai','chat','AI for building interactive game characters with voice and memory.','🗣️','https://convai.com',true,false,2400),
('latitude-ai','Latitude AI','latitude','chat','AI game platform for building text-based adventure games.','🗺️','https://latitude.io',true,false,1600),
('ai-dungeon','AI Dungeon','ai-dungeon','chat','AI-powered infinite text adventure game with unlimited storylines.','🐉','https://aidungeon.com',true,false,5200),
('scenario-gg','Scenario.gg','scenario','image','AI art generator specifically trained for consistent game asset creation.','🎮','https://scenario.gg',true,false,2900),
('ludo-ai','Ludo AI','ludo','research','AI game design tool for generating game concepts, mechanics, and assets.','🎲','https://ludo.ai',false,false,1800),
('unity-muse','Unity Muse','unity-muse','code','AI tools integrated into Unity game engine for generating game content.','🎯','https://unity.com/products/muse',false,false,3200),
('meshy-ai','Meshy AI','meshy','design','AI 3D model generator from text and image prompts for game assets.','🧊','https://meshy.ai',true,false,2600),
('spline-ai','Spline AI','spline','design','AI-powered 3D design tool for creating interactive web experiences.','🔮','https://spline.design',true,false,3100),
('kaedim','Kaedim','kaedim','design','AI that converts 2D concept art into production-ready 3D game models.','🎨','https://kaedim3d.com',false,false,1400),
('sloyd','Sloyd AI','sloyd','design','AI 3D modeler for creating game-ready props and assets via prompts.','🔷','https://sloyd.ai',true,false,1900),
('poly-pizza','Poly.pizza AI','poly-pizza','design','AI 3D asset library and generator for game developers.','🍕','https://poly.pizza',true,false,1200),
('kinetix','Kinetix','kinetix','video','AI motion capture tool creating game animations from video footage.','🕺','https://kinetix.tech',false,false,1600),
('reallusion-ai','Reallusion AI','reallusion','video','AI character animation platform for games, films, and virtual worlds.','🎭','https://reallusion.com',false,false,2400),
('didimo','Didimo AI','didimo','design','AI digital human generator for games, VR, and metaverse applications.','👤','https://didimo.co',false,false,1300),
('ready-player-me','Ready Player Me AI','ready-player-me','design','AI avatar creator for cross-game metaverse identity and customization.','🎮','https://readyplayer.me',true,false,3600),
('altered-ai','Altered.ai','altered-ai','audio','AI voice changer for gaming and streaming with real-time voice morphing.','🎙️','https://altered.ai',false,false,1900),
('epidemic-sound','Epidemic Sound AI','epidemic','audio','AI music and sound effects library for content creators and games.','🎵','https://epidemicsound.com',false,false,4200),
('artbreeder-collage','Artbreeder Collage','artbreeder-col','image','AI collage tool for combining images into new creative compositions.','🖼️','https://artbreeder.com/collage',true,false,1800),
('viverse','VIVERSE AI','viverse','chat','HTC''s AI-powered metaverse platform for virtual collaboration.','🌐','https://viverse.com',false,false,1100),

-- ━━━ HR & RECRUITMENT AI ━━━
('workday-ai','Workday AI','workday-ai','research','Enterprise AI platform for HR, finance, and workforce planning.','💼','https://workday.com',false,false,4800),
('paradox-ai','Paradox AI','paradox','research','AI recruiting assistant Olivia for automating candidate screening and scheduling.','🤖','https://paradox.ai',false,false,2100),
('eightfold-ai','Eightfold AI','eightfold','research','AI talent intelligence platform for hiring, retention, and workforce planning.','🌸','https://eightfold.ai',false,false,1800),
('pymetrics','Pymetrics AI','pymetrics','research','AI bias-free candidate assessment using neuroscience games.','🧠','https://pymetrics.ai',false,false,1600),
('hirevue','HireVue AI','hirevue','research','AI video interviewing platform with automated candidate scoring.','📹','https://hirevue.com',false,false,2400),
('talview','Talview AI','talview','research','AI recruitment platform for proctored assessments and video interviews.','👁️','https://talview.com',false,false,1400),
('mya-systems','Mya AI','mya','research','AI recruiting chatbot automating candidate engagement and scheduling.','💬','https://mya.com',false,false,1200),
('beamery','Beamery AI','beamery','research','AI talent lifecycle management platform for enterprises.','✨','https://beamery.com',false,false,1500),
('fetcher-ai','Fetcher AI','fetcher','research','AI candidate sourcing tool automating outreach for recruiters.','🔍','https://fetcher.ai',false,false,1900),
('karat-ai','Karat AI','karat','code','AI technical interview platform with pre-vetted software engineers.','🏅','https://karat.com',false,false,2200),
('hackerrank-ai','HackerRank AI','hackerrank','code','AI coding assessment platform for technical screening and interviews.','💻','https://hackerrank.com',true,false,4800),
('codility','Codility AI','codility','code','AI code testing platform for evaluating developer skills in hiring.','💡','https://codility.com',false,false,3100),
('vervoe','Vervoe AI','vervoe','research','AI hiring tool replacing resumes with job-specific skill assessments.','✅','https://vervoe.com',false,false,1300),
('jobscan-ai','Jobscan AI','jobscan','research','AI resume optimizer matching resumes to job descriptions for ATS.','📄','https://jobscan.co',true,false,3600),
('rezi-ai','Rezi AI','rezi','research','AI resume builder optimized for applicant tracking systems.','📝','https://rezi.ai',true,false,2800),
('kickresume','Kickresume AI','kickresume','research','AI resume and cover letter builder with GPT-4 content suggestions.','🦵','https://kickresume.com',true,false,2400),
('enhancv','Enhancv AI','enhancv','research','AI resume builder with impact statement suggestions and ATS scoring.','📊','https://enhancv.com',true,false,2100),
('teal-hq','Teal AI','teal','research','AI job search platform tracking applications and optimizing resumes.','🟢','https://tealhq.com',true,false,1900),
('careerflow','Careerflow AI','careerflow','research','AI LinkedIn optimizer and job application tracker for job seekers.','🌊','https://careerflow.ai',true,false,1600),
('linkedin-ai','LinkedIn AI','linkedin-ai','research','AI features in LinkedIn for job matching, writing assistance, and coaching.','💼','https://linkedin.com',true,true,18000),

-- ━━━ E-COMMERCE & SALES AI ━━━
('unbounce-ai','Unbounce AI','unbounce','marketing','AI landing page builder with smart conversion optimization features.','🚀','https://unbounce.com',false,false,3200),
('persado','Persado AI','persado','marketing','AI message optimization platform improving conversion through language.','📢','https://persado.com',false,false,1800),
('jasper-ai','Jasper AI','jasper','marketing','Leading AI marketing platform for brands creating consistent content.','🤖','https://jasper.ai',false,true,9800),
('hypotenuse-ai','Hypotenuse AI','hypotenuse','marketing','AI content writer for e-commerce product descriptions and blog posts.','💧','https://hypotenuse.ai',false,false,1900),
('aidaptive','Aidaptive','aidaptive','marketing','AI predictive personalization engine for e-commerce recommendations.','🎯','https://aidaptive.com',false,false,1100),
('vue-ai','Vue.ai','vue-ai','marketing','AI-powered retail automation for product tagging, recommendations, and visuals.','👗','https://vue.ai',false,false,1600),
('nosto','Nosto AI','nosto','marketing','AI personalization platform for e-commerce with product recommendations.','🛍️','https://nosto.com',false,false,2200),
('barilliance','Barilliance AI','barilliance','marketing','AI behavioral targeting for e-commerce personalization and cart recovery.','🛒','https://barilliance.com',false,false,1400),
('recombee','Recombee AI','recombee','research','AI recommendation engine API for e-commerce and media platforms.','🔄','https://recombee.com',true,false,1200),
('constructor-io','Constructor.io','constructorio','marketing','AI site search and product discovery platform for e-commerce.','🔍','https://constructor.io',false,false,1800),
('klevu','Klevu AI','klevu','marketing','AI smart search for e-commerce improving product discovery and conversion.','🔍','https://klevu.com',false,false,1500),
('yotpo-ai','Yotpo AI','yotpo','marketing','AI e-commerce marketing platform for reviews, loyalty, and SMS.','⭐','https://yotpo.com',false,false,2400),
('okendo','Okendo AI','okendo','marketing','AI customer review and loyalty platform for Shopify stores.','⭐','https://okendo.io',false,false,1600),
('gorgias-ai','Gorgias AI','gorgias','research','AI customer support helpdesk for e-commerce with automation rules.','💬','https://gorgias.com',false,false,2800),
('freshdesk-ai','Freshdesk AI','freshdesk','research','AI customer support platform with Freddy AI for ticket automation.','💧','https://freshworks.com/freshdesk',false,false,3600),
('zendesk-ai','Zendesk AI','zendesk','research','AI customer service platform with agent assist and ticket routing.','🔷','https://zendesk.com',false,false,5200),
('intercom-ai','Intercom AI','intercom','research','AI customer messaging platform with Fin AI agent for instant support.','💬','https://intercom.com',false,false,4800),
('drift-ai','Drift AI','drift','marketing','AI conversational marketing platform for B2B sales and lead capture.','💨','https://drift.com',false,false,3400),
('tidio-ai','Tidio AI','tidio','research','AI chatbot and live chat platform for small business customer service.','🤖','https://tidio.com',true,false,3100),
('chatfuel-ai','Chatfuel AI','chatfuel','automation','AI chatbot builder for Facebook Messenger and Instagram automation.','⛽','https://chatfuel.com',true,false,2800),

-- ━━━ CYBERSECURITY & PRIVACY AI ━━━
('darktrace','Darktrace AI','darktrace','research','AI cybersecurity platform using self-learning to detect cyber threats.','🛡️','https://darktrace.com',false,false,3800),
('crowdstrike-ai','CrowdStrike AI','crowdstrike','research','AI-native cybersecurity platform for endpoint and cloud protection.','🦅','https://crowdstrike.com',false,false,4200),
('sentinelone','SentinelOne AI','sentinelone','research','AI autonomous cybersecurity platform for endpoint and cloud security.','👁️','https://sentinelone.com',false,false,3600),
('cylance-ai','Cylance AI','cylance','research','AI-powered endpoint security using machine learning for threat prevention.','⚫','https://blackberry.com/cylance',false,false,2100),
('vectra-ai','Vectra AI','vectra','research','AI network detection and response platform for hybrid cloud attacks.','🔍','https://vectra.ai',false,false,2400),
('exabeam-ai','Exabeam AI','exabeam','research','AI SIEM platform with behavioral analytics for security operations.','📊','https://exabeam.com',false,false,1900),
('recorded-future','Recorded Future AI','recorded-future','research','AI threat intelligence platform analyzing billions of data points daily.','🔮','https://recordedfuture.com',false,false,2800),
('perception-point','Perception Point AI','perceptionpt','research','AI email and web browser security preventing phishing and malware.','🎯','https://perception-point.io',false,false,1600),
('abnormal-security','Abnormal Security AI','abnormal','research','AI email security platform detecting account takeovers and phishing.','🚫','https://abnormalsecurity.com',false,false,2100),
('ironscales','IRONSCALES AI','ironscales','research','AI anti-phishing platform combining human and machine threat detection.','⚔️','https://ironscales.com',false,false,1400),
('private-ai','Private AI','private-ai','research','AI data privacy tool detecting and anonymizing PII in documents.','🔒','https://private-ai.com',false,false,1800),
('skyflow-ai','Skyflow AI','skyflow','research','AI data privacy vault for storing and managing sensitive PII data.','☁️','https://skyflow.com',false,false,1200),
('nightfall-ai','Nightfall AI','nightfall','research','AI data loss prevention platform scanning cloud apps for sensitive data.','🌃','https://nightfall.ai',false,false,1500),
('securiti','Securiti AI','securiti','research','AI-powered data security and privacy compliance management platform.','🛡️','https://securiti.ai',false,false,1900),
('verisoul','Verisoul AI','verisoul','research','AI fraud prevention platform detecting fake accounts and bot activity.','✅','https://verisoul.ai',false,false,1100),
('sift-science','Sift AI','sift','research','AI fraud detection platform for payment and account fraud prevention.','⚡','https://sift.com',false,false,2400),
('kount-ai','Kount AI','kount','research','AI fraud and identity trust platform for digital commerce.','🔐','https://kount.com',false,false,1800),
('sardine-ai','Sardine AI','sardine','finance','AI fraud prevention and compliance platform for fintech companies.','🐟','https://sardine.ai',false,false,1300),
('riskified','Riskified AI','riskified','finance','AI chargeback guarantee platform for e-commerce fraud protection.','🛡️','https://riskified.com',false,false,1600),
('forter','Forter AI','forter','finance','AI identity-based fraud prevention for digital commerce transactions.','🔒','https://forter.com',false,false,1900),

-- ━━━ TRAVEL & LIFESTYLE AI ━━━
('roam-ai','Roam AI','roam-ai','research','AI travel planner creating personalized itineraries from preferences.','🗺️','https://roamaround.io',true,false,1800),
('curiosio','Curiosio AI','curiosio','research','AI road trip planner generating optimized routes and points of interest.','🚗','https://curiosio.com',true,false,1200),
('tripnotes','TripNotes AI','tripnotes','research','AI-powered travel journal and itinerary builder for travelers.','📔','https://tripnotes.ai',true,false,900),
('wanderlog','Wanderlog AI','wanderlog','research','AI travel planner for creating and collaborating on trip itineraries.','✈️','https://wanderlog.com',true,false,3200),
('travelperk-ai','TravelPerk AI','travelperk','research','AI business travel management platform for expense and booking.','✈️','https://travelperk.com',false,false,2800),
('kayak-ai','Kayak AI','kayak','research','AI travel search with price prediction and trip planning features.','🏄','https://kayak.com',true,false,6800),
('hopper-ai','Hopper AI','hopper','research','AI flight and hotel price prediction app for booking at the best time.','🐇','https://hopper.com',true,false,5200),
('rome2rio-ai','Rome2rio AI','rome2rio','research','AI multi-transport route planner showing all travel options globally.','🌍','https://rome2rio.com',true,false,3600),
('lovo-fitness','Lova Fitness AI','lova','healthcare','AI personal fitness trainer creating adaptive workout and diet plans.','💪','https://lova.ai',true,false,1400),
('whoop-ai','WHOOP AI','whoop','healthcare','AI fitness wearable analyzing recovery, strain, and sleep scores.','⌚','https://whoop.com',false,false,3800),
('oura-ai','Oura AI','oura','healthcare','AI health ring tracking sleep, readiness, and activity with insights.','💍','https://ouraring.com',false,false,4200),
('fitbod-ai','Fitbod AI','fitbod','healthcare','AI personal strength training app adapting workouts to recovery.','🏋️','https://fitbod.me',false,false,2600),
('myfitnesspal-ai','MyFitnessPal AI','myfitnesspal','healthcare','AI calorie counter and nutrition tracker with food database.','🥗','https://myfitnesspal.com',true,false,5800),
('cronometer','Cronometer AI','cronometer','healthcare','AI-powered nutrition tracker with detailed micronutrient analysis.','⏱️','https://cronometer.com',true,false,2200),
('lose-it','Lose It! AI','loseit','healthcare','AI weight loss app with food logging, calorie tracking, and insights.','📉','https://loseit.com',true,false,3100),
('foodsmart','Foodsmart AI','foodsmart','healthcare','AI dietitian platform for personalized nutrition recommendations.','🥦','https://foodsmart.com',false,false,1200),
('yummly','Yummly AI','yummly','research','AI recipe recommendation platform personalizing meal suggestions.','🍳','https://yummly.com',true,false,2800),
('plantjammer','Plant Jammer AI','plantjammer','research','AI chef teaching plant-based cooking through personalized recipes.','🌿','https://plantjammer.com',false,false,1100),
('whisk-ai','Whisk AI','whisk','research','AI recipe manager and meal planner with automatic grocery lists.','🥄','https://whisk.com',true,false,1800),
('mealprepai','MealPrepAI','mealprepai','research','AI meal prep planner generating weekly menus with shopping lists.','🍱','https://mealprepai.com',true,false,900),

-- ━━━ LEGAL & COMPLIANCE AI ━━━
('casetext','Casetext AI','casetext','research','AI legal research platform with CoCounsel GPT-4 for lawyers.','⚖️','https://casetext.com',false,false,2400),
('harvey-ai','Harvey AI','harvey','research','AI for law firms automating contract review, legal research, and drafting.','⚖️','https://harvey.ai',false,false,2100),
('lexion','Lexion AI','lexion','research','AI contract management platform with automated risk extraction.','📄','https://lexion.ai',false,false,1600),
('ironclad-ai','Ironclad AI','ironclad','research','AI-powered contract lifecycle management for legal and ops teams.','🔒','https://ironcladapp.com',false,false,2200),
('spellbook-ai','Spellbook AI','spellbook','research','AI contract drafting and review tool built on GPT-4 for lawyers.','📖','https://spellbook.legal',false,false,1800),
('klarity-ai','Klarity AI','klarity','research','AI contract review platform extracting key terms and obligations.','💡','https://klarity.ai',false,false,1400),
('kira-ai','Kira AI','kira','research','AI machine learning tool for reviewing and analyzing legal contracts.','🔍','https://kirasystems.com',false,false,1900),
('termsservice','Terms.ai','terms-ai','research','AI tool generating privacy policies and terms of service for businesses.','📋','https://terms.ai',true,false,2100),
('complai','Compl.ai','complai','research','AI compliance assistant helping businesses stay regulation compliant.','✅','https://compl.ai',false,false,1200),
('gpt-lawyer','GPT Lawyer','gpt-lawyer','research','AI legal assistant for answering legal questions and drafting documents.','⚖️','https://gptlawyer.io',true,false,1600),
('patentpal','PatentPal','patentpal','research','AI tool automating mechanical parts of patent application writing.','📝','https://patentpal.com',true,false,1100),
('specifio','Specifio AI','specifio','research','AI patent drafting platform generating first-draft patent applications.','📄','https://specifio.com',false,false,900),
('veritone-ai','Veritone AI','veritone','research','AI media platform for cognitive analysis of audio, video, and data.','🔬','https://veritone.com',false,false,1800),
('eigen-ai','Eigen Technologies','eigen','finance','AI document intelligence platform for financial services and law firms.','📊','https://eigentech.com',false,false,1400),
('docugami','Docugami AI','docugami','research','AI document engineering platform transforming documents into structured data.','📁','https://docugami.com',false,false,1100),
('luminance','Luminance AI','luminance','research','AI legal document analysis platform using deep learning for review.','💡','https://luminance.com',false,false,1600),
('thinkon-ai','ThinkOn AI','thinkon','research','Canadian AI-powered data management and compliance cloud platform.','🍁','https://thinkon.com',false,false,800),
('notabot','Nota AI','notabot','research','AI platform for automating legal workflows and compliance tasks.','📔','https://nota.ai',false,false,900),
('evisort','Evisort AI','evisort','research','AI contract intelligence platform for tracking obligations and renewals.','📊','https://evisort.com',false,false,1300),
('contractbook','Contractbook AI','contractbook','research','AI contract management platform from creation to data extraction.','📗','https://contractbook.com',false,false,1700),

-- ━━━ SCIENCE & DATA AI ━━━
('julius-ai','Julius AI','julius','research','AI data analyst — upload spreadsheets and charts, ask questions in plain English.','📊','https://julius.ai',true,true,5800),
('obviously-ai','Obviously AI','obviously','research','No-code predictive analytics platform for non-technical business users.','🔮','https://obviously.ai',false,false,1800),
('akkio','Akkio AI','akkio','research','No-code AI platform for building predictive models from business data.','🌊','https://akkio.com',true,false,2100),
('datarobot','DataRobot AI','datarobot','research','Enterprise AI platform for automating the full ML model lifecycle.','🤖','https://datarobot.com',false,false,3600),
('h2o-ai','H2O.ai','h2o','research','Open-source AI and ML platform for building predictive models.','💧','https://h2o.ai',true,false,2800),
('dataiku','Dataiku AI','dataiku','research','Enterprise AI platform for preparing, building, and deploying ML models.','📊','https://dataiku.com',false,false,3200),
('domino-data','Domino Data Lab','domino','research','Enterprise MLOps platform for managing data science teams.','🎲','https://dominodatalab.com',false,false,2100),
('weights-biases','Weights & Biases','wandb','code','AI developer platform for experiment tracking, model training, and evaluation.','⚖️','https://wandb.ai',true,false,4200),
('mlflow','MLflow','mlflow','code','Open-source ML lifecycle management platform for tracking experiments.','🔄','https://mlflow.org',true,false,3800),
('neptune-ai','Neptune.ai','neptune','code','AI experiment tracking and model registry for ML teams.','🔱','https://neptune.ai',true,false,2400),
('comet-ml','Comet ML','comet','code','AI model evaluation and experiment tracking platform for teams.','☄️','https://comet.com',true,false,2100),
('dvc-ai','DVC','dvc','code','Open-source ML experiment tracking and data versioning system.','📦','https://dvc.org',true,false,2800),
('evidently-ai','Evidently AI','evidently','research','Open-source ML model monitoring for detecting drift and quality issues.','📊','https://evidentlyai.com',true,false,2200),
('arize-ai','Arize AI','arize','research','ML observability platform for monitoring model performance in production.','🔭','https://arize.com',true,false,1800),
('fiddler-ai','Fiddler AI','fiddler','research','AI model performance and explainability monitoring platform.','🎻','https://fiddler.ai',false,false,1400),
('scale-ai','Scale AI','scale','research','AI data labeling and RLHF platform powering the world''s leading AI companies.','📏','https://scale.com',false,false,4800),
('labelbox','Labelbox AI','labelbox','research','AI training data platform for labeling images, video, and text.','🏷️','https://labelbox.com',true,false,2600),
('roboflow','Roboflow','roboflow','code','Computer vision platform for building and deploying image AI models.','🤖','https://roboflow.com',true,false,3400),
('landing-ai','Landing AI','landing-ai','research','Andrew Ng''s AI company offering LandingLens for visual inspection.','🛬','https://landing.ai',false,false,2100),
('appen','Appen AI','appen','research','AI training data collection and annotation platform for global teams.','🌐','https://appen.com',false,false,2400)

ON CONFLICT (id) DO NOTHING;
