-- SYNAP AI TOOLS — BATCH 6 (200 famous tools)
INSERT INTO public.ai_tools (id,name,slug,category_id,description,icon_emoji,website_url,has_free_tier,is_featured,click_count) VALUES

-- ━━━ TOP CHAT & ASSISTANTS ━━━
('chatgpt','ChatGPT','chatgpt','chat','OpenAI flagship AI chatbot with GPT-4o, reasoning, and image generation.','🤖','https://chat.openai.com',true,true,95000),
('claude','Claude','claude','chat','Anthropic AI assistant with strong reasoning and 200K context window.','🧠','https://claude.ai',true,true,42000),
('gemini','Google Gemini','gemini','chat','Google AI assistant powered by Gemini Ultra with multimodal abilities.','✨','https://gemini.google.com',true,true,38000),
('perplexity','Perplexity AI','perplexity','chat','AI search engine providing cited answers from real-time web sources.','🔍','https://perplexity.ai',true,true,28000),
('copilot','Microsoft Copilot','copilot','chat','Microsoft AI assistant with GPT-4, DALL-E, and Office integration.','🤝','https://copilot.microsoft.com',true,true,32000),
('pi-ai','Pi by Inflection','pi-ai','chat','Personal AI companion focused on being empathetic and conversational.','🥧','https://pi.ai',true,false,8400),
('you-chat','You.com AI','you-chat','chat','AI search engine with chat, code, and image generation built in.','🔎','https://you.com',true,false,5200),
('phind','Phind','phind','chat','AI search engine built specifically for developers and programming.','💻','https://phind.com',true,false,6800),
('mistral-chat','Mistral Le Chat','mistral-chat','chat','Mistral AI chat with open-weight models for fast reasoning.','🌬️','https://chat.mistral.ai',true,false,4600),
('coze','Coze','coze','chat','ByteDance AI bot building platform with plugins and workflows.','🤖','https://coze.com',true,false,3200),
('huggingchat','HuggingChat','huggingchat','chat','Open-source AI chat by HuggingFace running Llama and Mistral models.','🤗','https://huggingface.co/chat',true,false,4800),
('together-ai','Together AI','together-ai','chat','Platform running 100+ open-source LLMs with fastest inference.','🤝','https://together.ai',true,false,3600),
('anyscale','Anyscale','anyscale','chat','Enterprise platform for deploying and scaling open-source LLMs.','🔷','https://anyscale.com',false,false,2200),
('fireworks-ai','Fireworks AI','fireworks','chat','Fast inference platform for open-source models with function calling.','🎆','https://fireworks.ai',true,false,2800),

-- ━━━ TOP WRITING TOOLS ━━━
('copy-ai','Copy.ai','copy-ai','writing','AI copywriting tool for marketing, blogs, social media, and ads.','📝','https://copy.ai',true,true,12000),
('writesonic','Writesonic','writesonic','writing','AI writing and SEO tool with blog generator and brand voice.','✍️','https://writesonic.com',true,false,8200),
('rytr','Rytr','rytr','writing','AI writing assistant generating content in 30+ languages cheaply.','📄','https://rytr.me',true,false,5400),
('sudowrite','Sudowrite','sudowrite','writing','AI creative writing partner for fiction authors and novelists.','📖','https://sudowrite.com',false,false,3200),
('novelai','NovelAI','novelai','writing','AI storytelling platform for writing fiction with custom models.','📚','https://novelai.net',false,false,4800),
('anyword','Anyword','anyword','writing','AI copywriting with predictive performance scoring for marketing.','📊','https://anyword.com',true,false,2800),
('writer-ai','Writer','writer-ai','writing','Enterprise AI writing platform with brand voice and style guides.','✏️','https://writer.com',false,false,3600),
('hyperwrite','HyperWrite','hyperwrite','writing','AI writing assistant with AutoWrite and research capabilities.','⚡','https://hyperwriteai.com',true,false,2400),
('peppertype','Peppertype','peppertype','writing','AI content generation for blogs, ads, and product descriptions.','🌶️','https://peppertype.ai',true,false,1800),
('ink-editor','INK Editor','ink-editor','writing','AI SEO writing tool optimizing content for search rankings.','🖋️','https://inkforall.com',true,false,2200),
('hemingway-ai','Hemingway Editor','hemingway','writing','AI writing tool making prose bold and clear with readability scores.','📝','https://hemingwayapp.com',true,false,4200),
('prowritingaid','ProWritingAid','prowritingaid','writing','AI grammar checker and style editor for authors and professionals.','✅','https://prowritingaid.com',true,false,3800),
('languagetool','LanguageTool','languagetool','writing','Open-source AI grammar and spell checker supporting 30+ languages.','🔤','https://languagetool.org',true,false,5600),
('textcortex','TextCortex','textcortex','writing','AI writing assistant with knowledge base and custom personas.','🧠','https://textcortex.com',true,false,1600),
('simplified-ai','Simplified AI','simplified','writing','All-in-one AI design and writing tool for marketing teams.','🎨','https://simplified.com',true,false,2800),
('scalenut','Scalenut','scalenut','writing','AI SEO content platform with keyword planning and writing.','📈','https://scalenut.com',true,false,2100),
('longshot','LongShot AI','longshot','writing','AI blog writer with fact-checking and SEO optimization.','🎯','https://longshot.ai',true,false,1400),
('frase','Frase','frase','writing','AI SEO content tool with SERP analysis and content briefs.','🔍','https://frase.io',false,false,2600),
('surfer-seo','Surfer SEO','surfer','writing','AI content optimization tool scoring pages against top results.','🏄','https://surferseo.com',false,false,4200),
('clearscope','Clearscope','clearscope','writing','AI content optimization platform for SEO-driven writing.','🔎','https://clearscope.io',false,false,2400),

-- ━━━ TOP IMAGE GENERATION ━━━
('midjourney','Midjourney','midjourney','image','Premier AI art generator creating stunning images via Discord.','🎨','https://midjourney.com',false,true,45000),
('dall-e','DALL-E 3','dall-e','image','OpenAI image generator with precise text rendering and creativity.','🖼️','https://openai.com/dall-e-3',true,true,32000),
('stable-diffusion','Stable Diffusion','stable-diffusion','image','Open-source AI image generator by Stability AI with full control.','🎭','https://stability.ai',true,true,28000),
('leonardo-ai','Leonardo.AI','leonardo-ai','image','AI image generation platform with fine-tuned models for games and art.','🎨','https://leonardo.ai',true,true,16000),
('flux-ai','Flux AI','flux-ai','image','Black Forest Labs AI image model with photorealistic generation.','⚡','https://blackforestlabs.ai',true,false,8200),
('playground-ai','Playground AI','playground-ai','image','Free AI image generator with editing canvas and mixed models.','🎮','https://playground.ai',true,false,6400),
('nightcafe','NightCafe','nightcafe','image','AI art generator with multiple algorithms and community gallery.','🌙','https://nightcafe.studio',true,false,4800),
('clipdrop','ClipDrop','clipdrop','image','Stability AI tool suite for background removal, upscaling, relighting.','✂️','https://clipdrop.co',true,false,5200),
('krea-ai','Krea AI','krea-ai','image','Real-time AI image generation with canvas editing and upscaling.','🎨','https://krea.ai',true,false,3600),
('tensor-art','Tensor.Art','tensor-art','image','Free AI image generator with thousands of community-trained models.','🎨','https://tensor.art',true,false,4200),
('civitai','CivitAI','civitai','image','Community hub for Stable Diffusion models, LoRAs, and prompts.','🎭','https://civitai.com',true,false,8800),
('lexica','Lexica','lexica','image','AI image search engine and generator with Aperture model.','🔍','https://lexica.art',true,false,3800),
('photosonic','Photosonic','photosonic','image','AI art generator by Writesonic for creating images from text.','📸','https://photosonic.ai',true,false,2400),
('getimg','Getimg.ai','getimg','image','AI image toolkit with generation, editing, and model training.','🖼️','https://getimg.ai',true,false,2800),
('dpth-ai','Dpth AI','dpth','image','AI 3D photo effect generator creating depth maps from 2D images.','📷','https://dpth.app',true,false,1200),

-- ━━━ TOP VIDEO AI ━━━
('runway','Runway ML','runway','video','AI video generation platform with Gen-3 Alpha for filmmakers.','🎬','https://runwayml.com',true,true,18000),
('pika','Pika','pika','video','AI video generator creating and editing videos from text and images.','⚡','https://pika.art',true,true,12000),
('synthesia','Synthesia','synthesia','video','AI video creator with realistic avatars speaking 130+ languages.','🤖','https://synthesia.io',false,true,9800),
('heygen','HeyGen','heygen','video','AI video creator with talking avatars and voice cloning.','🎥','https://heygen.com',true,true,8400),
('lumen5','Lumen5','lumen5','video','AI video maker turning blog posts into engaging social videos.','💡','https://lumen5.com',true,false,5200),
('pictory','Pictory AI','pictory','video','AI turning long videos and blogs into short viral clips.','📹','https://pictory.ai',true,false,4200),
('fliki','Fliki','fliki','video','AI text-to-video creator with lifelike voiceovers and stock media.','🎬','https://fliki.ai',true,false,3800),
('veed-ai','VEED.IO','veed','video','Online AI video editor with subtitles, effects, and transcription.','🎥','https://veed.io',true,false,6800),
('kapwing-ai','Kapwing AI','kapwing','video','AI video editor with auto-subtitles, resizing, and smart cut.','🎬','https://kapwing.com',true,false,5400),
('wondershare-ai','Filmora AI','filmora','video','AI desktop video editor with motion tracking and auto-reframe.','🎞️','https://filmora.wondershare.com',false,false,4800),
('topaz-video','Topaz Video AI','topaz-video','video','AI video upscaler enhancing resolution up to 8K with deinterlacing.','🎥','https://topazlabs.com/topaz-video-ai',false,false,3600),
('colossyan','Colossyan','colossyan','video','AI video creator for corporate learning and training content.','🏢','https://colossyan.com',false,false,2400),
('steve-ai','Steve AI','steve','video','AI animated and live-action video maker from text scripts.','🤖','https://steve.ai',true,false,2800),
('elai-io','Elai.io','elai','video','AI video platform with custom avatars and multilingual generation.','🎥','https://elai.io',false,false,2200),
('d-id','D-ID','d-id','video','AI talking head video creator animating photos with speech.','👤','https://d-id.com',true,false,3200),
('kaiber','Kaiber','kaiber','video','AI video generation for music videos and artistic animations.','🎨','https://kaiber.ai',false,false,2600),
('vidnoz','Vidnoz AI','vidnoz','video','Free AI video creator with 800+ templates and avatars.','🎬','https://vidnoz.com',true,false,2000),
('submagic','Submagic','submagic','video','AI auto-subtitle generator with trendy animated captions.','💬','https://submagic.co',true,false,3400),
('captions-ai','Captions App','captions','video','AI video editing app with auto-captions, eye contact fix, teleprompter.','📱','https://captions.ai',true,false,4800),
('autocut','AutoCut','autocut','video','AI Premiere Pro plugin removing silences and adding captions.','✂️','https://autocut.fr',false,false,1800),

-- ━━━ TOP AUDIO & VOICE AI ━━━
('elevenlabs','ElevenLabs','elevenlabs','audio','Premium AI voice generator with ultra-realistic text-to-speech.','🎙️','https://elevenlabs.io',true,true,18000),
('murf-ai','Murf AI','murf-ai','audio','AI voiceover platform with 120+ realistic voices in 20 languages.','🎤','https://murf.ai',true,false,6200),
('play-ht','Play.ht','play-ht','audio','AI text-to-speech with voice cloning and podcast generation.','▶️','https://play.ht',true,false,4800),
('resemble-ai','Resemble AI','resemble','audio','AI voice cloning platform creating custom synthetic voices.','🔊','https://resemble.ai',false,false,2800),
('wellsaid','WellSaid Labs','wellsaid','audio','Enterprise AI voice generator for corporate training and content.','🗣️','https://wellsaidlabs.com',false,false,2400),
('coqui','Coqui AI','coqui','audio','Open-source AI text-to-speech with voice cloning capabilities.','🐸','https://coqui.ai',true,false,2200),
('podcast-ai','Podcast AI','podcast-ai','audio','AI generating new podcast episodes from voice clones of hosts.','🎧','https://podcast.ai',true,false,1600),
('soundraw','Soundraw','soundraw','audio','AI music generator creating royalty-free tracks for content creators.','🎵','https://soundraw.io',true,false,3200),
('aiva','AIVA','aiva','audio','AI music composer creating emotional soundtracks for any media.','🎼','https://aiva.ai',true,false,2800),
('boomy','Boomy','boomy','audio','AI music creation platform publishing songs to Spotify and Apple Music.','🎶','https://boomy.com',true,false,3600),
('lalal-ai','LALAL.AI','lalal','audio','AI vocal and instrument separator extracting stems from any song.','🎵','https://lalal.ai',true,false,4200),
('vocalize-ai','Vocalize AI','vocalize','audio','AI voice changer for real-time voice transformation in calls.','🎭','https://vocalize.im',true,false,1800),
('voicemod-ai','Voicemod AI','voicemod','audio','Real-time AI voice changer for gaming, streaming, and calls.','🎮','https://voicemod.net',true,false,5200),
('lyrebird','Descript Lyrebird','lyrebird','audio','AI voice synthesis creating realistic voice clones for editing.','🐦','https://descript.com',true,false,2600),
('beatoven','Beatoven.ai','beatoven','audio','AI music generator creating mood-based royalty-free soundtracks.','🎼','https://beatoven.ai',true,false,1800),

-- ━━━ TOP CODE & DEV ━━━
('windsurf','Windsurf','windsurf','code','AI-native code editor by Codeium with Cascade autonomous agent.','🏄','https://codeium.com/windsurf',true,true,8200),
('tabnine','Tabnine','tabnine','code','AI code completion running locally with privacy-first approach.','🔷','https://tabnine.com',true,false,6800),
('pieces','Pieces for Developers','pieces','code','AI developer productivity tool saving and enriching code snippets.','🧩','https://pieces.app',true,false,2800),
('blackbox-ai','Blackbox AI','blackbox','code','AI code generation and search for developers with IDE extension.','⬛','https://blackbox.ai',true,false,4200),
('continue-dev','Continue','continue-dev','code','Open-source AI code assistant for VS Code and JetBrains.','🔄','https://continue.dev',true,false,3200),
('aider','Aider','aider','code','AI pair programming in terminal with git integration and diff editing.','💬','https://aider.chat',true,false,4800),
('sourcegraph','Sourcegraph','sourcegraph','code','AI code intelligence platform searching across all repositories.','🔍','https://sourcegraph.com',true,false,3600),
('snyk-ai','Snyk AI','snyk','code','AI security platform finding and fixing code vulnerabilities.','🛡️','https://snyk.io',true,false,4200),
('sonarqube-ai','SonarQube AI','sonarqube','code','AI code quality and security analysis for continuous inspection.','📊','https://sonarqube.org',true,false,3800),
('vercel-ai','Vercel AI SDK','vercel-ai','code','AI toolkit for building AI-powered web applications with React.','▲','https://sdk.vercel.ai',true,false,5200),
('huggingface','Hugging Face','huggingface','code','AI model hub hosting 500K+ models, datasets, and ML spaces.','🤗','https://huggingface.co',true,true,22000),
('replicate','Replicate','replicate','code','Cloud API running open-source AI models with one line of code.','🔁','https://replicate.com',true,false,6400),
('modal','Modal','modal','code','Serverless cloud for running AI/ML workloads with GPU access.','🔷','https://modal.com',true,false,3200),
('weights-biases','Weights & Biases','wandb','code','AI experiment tracking and ML ops platform for teams.','📊','https://wandb.ai',true,false,4800),
('lightning-ai','Lightning AI','lightning','code','AI platform for training and deploying models with PyTorch.','⚡','https://lightning.ai',true,false,3600),

-- ━━━ TOP MARKETING & SEO ━━━
('brandmark','Brandmark','brandmark','marketing','AI logo maker generating unique brand identities instantly.','🎨','https://brandmark.io',false,false,2800),
('designs-ai','Designs.ai','designs-ai','marketing','AI design suite for logos, videos, mockups, and social media.','🎨','https://designs.ai',true,false,2400),
('predis','Predis.ai','predis','marketing','AI social media content generator with scheduling and analytics.','📱','https://predis.ai',true,false,3200),
('lately-ai','Lately AI','lately','marketing','AI content repurposing tool turning long content into social posts.','🔄','https://lately.ai',false,false,1800),
('ocoya','Ocoya','ocoya','marketing','AI social media management with content creation and scheduling.','🐙','https://ocoya.com',true,false,2600),
('hootsuite-ai','Hootsuite AI','hootsuite','marketing','AI social media management with smart scheduling and analytics.','🦉','https://hootsuite.com',false,false,6800),
('buffer-ai','Buffer AI','buffer','marketing','AI social media scheduling with content suggestions and analytics.','📊','https://buffer.com',true,false,5400),
('sprout-ai','Sprout Social AI','sprout','marketing','Enterprise AI social media management with listening and analytics.','🌱','https://sproutsocial.com',false,false,4200),
('canva-social','Canva Social','canva-social','marketing','AI social media design and scheduling within Canva platform.','🎨','https://canva.com',true,false,8200),
('loomly','Loomly AI','loomly','marketing','AI social media calendar with post ideas and approval workflow.','📅','https://loomly.com',false,false,2200),
('photoroom','PhotoRoom','photoroom','marketing','AI photo editor for e-commerce with background removal and staging.','📸','https://photoroom.com',true,true,7800),
('flair-ai','Flair AI','flair','marketing','AI product photography tool creating studio-quality shots instantly.','✨','https://flair.ai',true,false,2400),
('booth-ai','Booth.ai','booth','marketing','AI product photography generator for e-commerce brands.','📷','https://booth.ai',false,false,1600),
('pencil-ai','Pencil AI','pencil','marketing','AI ad creative generator using winning formulas and A/B testing.','✏️','https://trypencil.com',false,false,2200),
('narrato','Narrato AI','narrato','marketing','AI content workspace for planning, creating, and publishing.','📝','https://narrato.io',true,false,1800)

ON CONFLICT (id) DO NOTHING;
