-- SYNAP AI TOOLS — BATCH 5 (200 tools)
-- Run in Supabase SQL Editor AFTER Batch 1, 2, 3 & 4
INSERT INTO public.ai_tools (id,name,slug,category_id,description,icon_emoji,website_url,has_free_tier,is_featured,click_count) VALUES

-- ━━━ BUSINESS INTELLIGENCE & ANALYTICS ━━━
('tableau-ai','Tableau AI','tableau','research','AI-powered data visualization and business intelligence platform.','📊','https://tableau.com',false,true,8900),
('powerbi-ai','Power BI AI','powerbi','research','Microsoft AI analytics platform for interactive data visualization.','📈','https://powerbi.microsoft.com',true,true,9200),
('looker-ai','Looker AI','looker','research','Google Cloud BI platform with AI-powered data exploration and analytics.','🔍','https://looker.com',false,false,5800),
('domo-ai','Domo AI','domo','research','AI-powered business intelligence platform with real-time data cards.','🔷','https://domo.com',false,false,3200),
('sisense','Sisense AI','sisense','research','AI-driven BI platform for embedding analytics into applications.','💡','https://sisense.com',false,false,2800),
('thoughtspot','ThoughtSpot AI','thoughtspot','research','AI-powered search analytics letting you query data in plain English.','💭','https://thoughtspot.com',false,false,2400),
('qlik-ai','Qlik AI','qlik','research','AI augmented analytics platform with associative data engine.','🔷','https://qlik.com',false,false,3600),
('metabase-ai','Metabase AI','metabase','research','Open-source BI tool with AI question suggestions and auto-charts.','🗂️','https://metabase.com',true,false,3800),
('superset-ai','Apache Superset AI','superset','research','Open-source data exploration and visualization platform with AI features.','🔧','https://superset.apache.org',true,false,2600),
('redash-ai','Redash AI','redash','research','Open-source tool for querying databases and building dashboards.','📊','https://redash.io',true,false,2100),
('hex-ai','Hex AI','hex','research','AI collaborative data workspace for SQL, Python, and visualization.','⬡','https://hex.tech',true,false,2800),
('mode-ai','Mode AI','mode','research','AI analytics platform combining SQL, Python, and data storytelling.','📊','https://mode.com',false,false,2200),
('census-ai','Census AI','census','research','Reverse ETL platform syncing data warehouse data to business tools.','📊','https://getcensus.com',false,false,1600),
('fivetran-ai','Fivetran AI','fivetran','research','AI data movement platform automating pipelines from 500+ sources.','🚰','https://fivetran.com',false,false,2400),
('airbyte','Airbyte AI','airbyte','research','Open-source data integration platform with AI-powered connector builder.','✈️','https://airbyte.com',true,false,2900),
('dbt-cloud','dbt Cloud AI','dbt','code','AI data transformation platform for analytics engineering workflows.','🔧','https://getdbt.com',true,false,3400),
('snowflake-ai','Snowflake AI','snowflake','research','Cloud data platform with Cortex AI for analyzing and querying data.','❄️','https://snowflake.com',false,false,4800),
('databricks-ai','Databricks AI','databricks','research','Unified data analytics platform combining data lakes and AI workloads.','🧱','https://databricks.com',true,false,5200),
('bigquery-ai','BigQuery AI','bigquery','research','Google Cloud serverless data warehouse with Gemini AI integration.','🌐','https://cloud.google.com/bigquery',false,false,4200),
('amplitude-ai','Amplitude AI','amplitude','research','AI product analytics platform for understanding user behavior.','📈','https://amplitude.com',true,false,3600),

-- ━━━ CUSTOMER SERVICE & SUPPORT AI ━━━
('forethought-ai','Forethought AI','forethought','research','AI customer support tool for ticket routing, deflection, and agent assist.','🧠','https://forethought.ai',false,false,2100),
('ultimate-ai','Ultimate AI','ultimate','research','AI customer service automation platform for enterprise support teams.','⚡','https://ultimate.ai',false,false,1800),
('aisera','Aisera AI','aisera','research','Enterprise AI service management platform for IT and HR automation.','🌊','https://aisera.com',false,false,1600),
('cognigy','Cognigy AI','cognigy','research','Enterprise conversational AI platform for contact centers.','🧩','https://cognigy.com',false,false,2200),
('nice-cxone','NICE CXone AI','nice-cx','research','AI cloud contact center platform for omnichannel customer experience.','📞','https://nice.com/cxone',false,false,2800),
('genesys-ai','Genesys AI','genesys','research','AI-powered cloud contact center and customer experience platform.','⚙️','https://genesys.com',false,false,3200),
('five9-ai','Five9 AI','five9','research','AI cloud contact center with virtual agents and agent assist features.','5️⃣','https://five9.com',false,false,2100),
('talkdesk-ai','Talkdesk AI','talkdesk','research','AI cloud contact center platform with self-service automation.','📱','https://talkdesk.com',false,false,2400),
('liveperson-ai','LivePerson AI','liveperson','research','AI conversational platform for digital-first customer engagement.','💬','https://liveperson.com',false,false,2200),
('sprinklr-ai','Sprinklr AI','sprinklr','marketing','AI unified customer experience management platform for enterprises.','✨','https://sprinklr.com',false,false,3100),
('helpscout-ai','Help Scout AI','helpscout','research','AI customer service platform for email and chat support teams.','🔦','https://helpscout.com',true,false,2600),
('kayako-ai','Kayako AI','kayako','research','AI customer service platform unifying email, chat, and social support.','🌊','https://kayako.com',false,false,1400),
('userlike','Userlike AI','userlike','research','AI live chat and chatbot platform for customer service teams.','💬','https://userlike.com',true,false,1800),
('landbot-ai','Landbot AI','landbot','automation','No-code AI chatbot builder for lead generation and customer service.','🤖','https://landbot.io',true,false,2400),
('manychat-ai','ManyChat AI','manychat','automation','AI chatbot platform for Instagram, WhatsApp, and Facebook marketing.','💬','https://manychat.com',true,false,4200),
('botsify','Botsify AI','botsify','automation','AI chatbot builder for websites, Facebook, and WhatsApp.','🤖','https://botsify.com',false,false,1600),
('collect-chat','Collect.chat AI','collectchat','automation','AI chatbot for collecting leads and survey responses interactively.','💬','https://collect.chat',true,false,1200),
('surveymonkey-ai','SurveyMonkey Genius','surveymonkey','research','AI survey builder analyzing responses and suggesting smarter questions.','📋','https://surveymonkey.com',true,false,4800),
('typeform-ai','Typeform AI','typeform','research','AI conversational form builder for engaging surveys and data collection.','📝','https://typeform.com',true,false,5200),
('jotform-ai','Jotform AI','jotform','automation','AI form builder with smart field suggestions and chatbot forms.','📋','https://jotform.com',true,false,4600),

-- ━━━ REAL ESTATE AI ━━━
('zillow-ai','Zillow AI','zillow','finance','AI real estate platform with Zestimate property value predictions.','🏠','https://zillow.com',true,false,6800),
('trulia-ai','Trulia AI','trulia','finance','AI home search platform with neighborhood insights and recommendations.','🏡','https://trulia.com',true,false,4200),
('compass-ai','Compass AI','compass','finance','AI real estate platform helping agents and buyers with market analysis.','🧭','https://compass.com',false,false,3200),
('redfin-ai','Redfin AI','redfin','finance','AI-powered real estate brokerage with deal score predictions.','🔴','https://redfin.com',true,false,4800),
('opendoor-ai','Opendoor AI','opendoor','finance','AI instant home buying platform with algorithmic pricing.','🚪','https://opendoor.com',false,false,3600),
('matterport-ai','Matterport AI','matterport','design','AI 3D digital twin platform for virtual property tours and scanning.','🏠','https://matterport.com',false,false,2800),
('virtual-staging','Virtual Staging AI','virtual-staging','design','AI tool staging empty rooms with virtual furniture for real estate listings.','🛋️','https://virtualstagingai.app',false,false,2100),
('rex-ai','REX AI','rex','finance','AI real estate platform eliminating agents for direct home buying.','🔑','https://rex.com',false,false,1400),
('habito-ai','Habito AI','habito','finance','AI mortgage broker finding the best rates using machine learning.','💰','https://habito.com',false,false,1600),
('properly-ai','Properly AI','properly','finance','AI home buying and selling platform with guaranteed sale pricing.','🏘️','https://properly.ca',false,false,1100),
('reonomy','Reonomy AI','reonomy','finance','AI commercial real estate data and analytics platform for investors.','📊','https://reonomy.com',false,false,1800),
('propmodo-ai','Propmodo AI','propmodo','research','AI commercial real estate research and technology analysis platform.','🏢','https://propmodo.com',true,false,900),
('entera-ai','Entera AI','entera','finance','AI platform for institutional investors buying single-family homes.','🏠','https://entera.ai',false,false,1200),
('stessa-ai','Stessa AI','stessa','finance','AI rental property financial management tool for landlords.','🏠','https://stessa.com',true,false,1900),
('buildout-ai','Buildout AI','buildout','marketing','AI commercial real estate marketing and CRM platform.','🏗️','https://buildout.com',false,false,1300),

-- ━━━ AGRICULTURE & ENVIRONMENT AI ━━━
('climate-ai','ClimatAi','climatai','research','AI climate risk analytics for agriculture and supply chain planning.','🌍','https://climate.ai',false,false,1200),
('granular-ai','Granular AI','granular','research','AI precision agriculture platform for farm management and analytics.','🌾','https://granular.ag',false,false,1400),
('farmers-edge','Farmers Edge AI','farmers-edge','research','AI digital agriculture platform for precision farming decisions.','🚜','https://farmersedge.ca',false,false,1100),
('arable-ai','Arable AI','arable','research','AI crop monitoring sensors with plant microclimate data analytics.','🌱','https://arable.com',false,false,900),
('taranis-ai','Taranis AI','taranis','research','AI ultra-high resolution crop intelligence for early disease detection.','🌿','https://taranis.ag',false,false,1100),
('gamaya-ai','Gamaya AI','gamaya','research','AI hyperspectral imaging for crop health and disease monitoring.','🛸','https://gamaya.com',false,false,800),
('prospera-ai','Prospera AI','prospera','research','AI crop intelligence for precision growing in greenhouses.','🥬','https://prospera.ag',false,false,950),
('trace-genomics','Trace Genomics AI','trace-genomics','research','AI soil genomics platform revealing soil health for farmers.','🧬','https://tracegenomics.com',false,false,700),
('atlas-ai','Atlas AI','atlas-ai','research','AI geospatial analytics for sustainable agriculture and development.','🌏','https://atlasai.co',false,false,800),
('pachama-ai','Pachama AI','pachama','research','AI platform verifying forest carbon credits via satellite data.','🌳','https://pachama.com',false,false,1100),
('terrawatch-ai','TerraWatch AI','terrawatch','research','AI environmental monitoring platform for climate risk assessment.','🌍','https://terrawatch.space',false,false,700),
('planet-labs','Planet Labs AI','planet-labs','research','AI satellite imagery analytics for environmental monitoring.','🛰️','https://planet.com',false,false,1600),
('descartes-labs','Descartes Labs AI','descartes','research','AI geospatial analysis platform for agriculture and energy sectors.','🗺️','https://descarteslabs.com',false,false,1200),
('regrow-ag','Regrow AI','regrow','research','AI sustainable agriculture platform for soil carbon measurement.','🌿','https://regrow.ag',false,false,900),
('cropin-ai','CropIn AI','cropin','research','AI agritech platform for crop advisory and supply chain tracking.','🌾','https://cropin.com',false,false,1100),

-- ━━━ MANUFACTURING & INDUSTRIAL AI ━━━
('sight-machine','Sight Machine AI','sight-machine','research','AI manufacturing analytics platform for production optimization.','🏭','https://sightmachine.com',false,false,1400),
('uptake-ai','Uptake AI','uptake','research','AI industrial analytics platform for predictive maintenance.','⬆️','https://uptake.com',false,false,1600),
('c3-ai','C3.ai','c3-ai','research','Enterprise AI platform for digital transformation across industries.','☁️','https://c3.ai',false,false,2800),
('augury-ai','Augury AI','augury','research','AI machine health platform predicting equipment failures in production.','🔧','https://augury.com',false,false,1800),
('samsara-ai','Samsara AI','samsara','research','AI fleet and operations management platform with safety analytics.','🚛','https://samsara.com',false,false,2400),
('industrial-ai','GE Digital AI','ge-digital','research','Industrial AI platform for asset performance and operations management.','⚙️','https://ge.com/digital',false,false,1900),
('ptc-ai','PTC AI','ptc','research','AI industrial IoT and augmented reality platform for manufacturing.','🔷','https://ptc.com',false,false,2100),
('aveva-ai','AVEVA AI','aveva','research','AI industrial software for engineering, operations, and performance.','🏭','https://aveva.com',false,false,1700),
('cognite-ai','Cognite AI','cognite','research','AI industrial data platform for asset-heavy industries.','🔵','https://cognite.com',false,false,1500),
('palantir-foundry','Palantir Foundry AI','palantir-foundry','research','AI data integration platform for complex enterprise operations.','🔮','https://palantir.com/foundry',false,false,2200),
('seeq-ai','Seeq AI','seeq','research','AI analytics platform for process manufacturing and industrial data.','🔍','https://seeq.com',false,false,1300),
('aspentech-ai','AspenTech AI','aspentech','research','AI optimization software for energy, chemicals, and manufacturing.','⚗️','https://aspentech.com',false,false,1600),
('trimble-ai','Trimble AI','trimble','research','AI positioning and geospatial solutions for construction and agriculture.','📐','https://trimble.com',false,false,1900),
('hexagon-ai','Hexagon AI','hexagon','research','AI digital reality solutions for manufacturing, infrastructure, and safety.','⬡','https://hexagon.com',false,false,1700),
('bentley-ai','Bentley Systems AI','bentley','research','AI infrastructure engineering software for digital twin creation.','🏗️','https://bentley.com',false,false,1400),

-- ━━━ SOCIAL MEDIA CONTENT AI ━━━
('lumen5','Lumen5','lumen5','video','AI video creator turning blog posts and URLs into social media videos.','💡','https://lumen5.com',true,false,3400),
('wave-video','Wave.video AI','wave-video','video','AI online video maker for social media clips and ads.','🌊','https://wave.video',true,false,2200),
('rawshorts','RawShorts AI','rawshorts','video','AI animated video maker for explainer and whiteboard videos.','📝','https://rawshorts.com',true,false,1600),
('promo-ai','Promo.com AI','promo','video','AI video creation platform for social media marketing and ads.','📢','https://promo.com',true,false,2400),
('boosted-ai','Boosted AI','boosted','video','AI video maker for small business social media content creation.','🚀','https://boosted.ai',true,false,1800),
('picmonkey-ai','PicMonkey AI','picmonkey','design','AI-powered online photo editor for social media graphics.','🐒','https://picmonkey.com',false,false,2800),
('adobe-post','Adobe Express Post','adobe-post','design','AI social media graphic creator with templates for every platform.','🎨','https://express.adobe.com',true,false,5400),
('stencil-ai','Stencil AI','stencil','design','AI graphic design tool for bloggers and social media managers.','✏️','https://getstencil.com',true,false,1600),
('photopea-ai','Photopea AI','photopea','design','Free browser-based Photoshop alternative with AI-powered tools.','🖼️','https://photopea.com',true,false,4200),
('placeit','Placeit AI','placeit','design','AI mockup generator and logo maker for branding and marketing.','📱','https://placeit.net',true,false,3600),
('smartmockups','SmartMockups AI','smartmockups','design','AI product mockup platform for showcasing designs on real devices.','📱','https://smartmockups.com',true,false,2900),
('mediamodifier','Mediamodifier AI','mediamodifier','design','AI design tool for creating mockups, animations, and social content.','🎨','https://mediamodifier.com',true,false,1800),
('socialbu-ai','SocialBu AI','socialbu','marketing','AI social media management tool with content generation and scheduling.','📱','https://socialbu.com',true,false,1400),
('postly-ai','Postly AI','postly','marketing','AI social media scheduler with content creation and repurposing.','📅','https://postly.ai',true,false,1200),
('circleboom-ai','Circleboom AI','circleboom','marketing','AI social media management tool for Twitter/X and multiple platforms.','⭕','https://circleboom.com',true,false,1900),
('publer-ai','Publer AI','publer','marketing','AI social media scheduler with bulk scheduling and AI caption writer.','📤','https://publer.io',true,false,2100),
('sendible-ai','Sendible AI','sendible','marketing','AI social media management and reporting platform for agencies.','📡','https://sendible.com',false,false,2400),
('agorapulse-ai','Agorapulse AI','agorapulse','marketing','AI social media management with inbox, publishing, and analytics.','💚','https://agorapulse.com',false,false,2600),
('socialpilot-ai','SocialPilot AI','socialpilot','marketing','AI social media scheduling and analytics tool for small businesses.','✈️','https://socialpilot.co',false,false,2800),
('metricool-ai','Metricool AI','metricool','marketing','AI social media analytics and scheduling for all major platforms.','📊','https://metricool.com',true,false,2200),

-- ━━━ BROWSER & SEARCH AI ━━━
('arc-browser','Arc Browser AI','arc','code','AI-powered browser with built-in AI features for browsing and research.','🌐','https://arc.net',true,false,6800),
('brave-ai','Brave Leo AI','brave','chat','AI assistant integrated into Brave browser for private AI chat.','🦁','https://brave.com',true,false,5200),
('opera-aria','Opera Aria AI','aria','chat','Built-in AI assistant in Opera browser with ChatGPT and Claude access.','🎭','https://opera.com',true,false,3800),
('perplexity-pages','Perplexity Pages','perplexity-pages','research','AI tool creating comprehensive visual articles from research topics.','📄','https://perplexity.ai/pages',true,false,2400),
('exa-ai','Exa AI','exa','research','AI semantic search API for finding relevant web content by meaning.','🔍','https://exa.ai',true,false,2100),
('kagi-ai','Kagi AI','kagi','research','Premium AI-powered search engine with no ads and personalization.','🔍','https://kagi.com',false,false,2600),
('andi-search','Andi Search AI','andi','research','Conversational AI search engine with summarized, cited answers.','💬','https://andisearch.com',true,false,1800),
('phind-api','Phind API','phind-api','code','AI search engine API for developers finding technical documentation.','🔎','https://phind.com/api',true,false,1600),
('metaphor-ai','Metaphor AI','metaphor','research','AI search API for finding content based on semantic similarity.','🦋','https://metaphor.systems',true,false,1400),
('tavily-ai','Tavily AI','tavily','research','AI search API optimized for AI agents needing web information.','🔍','https://tavily.com',true,false,1900),
('serper-ai','Serper AI','serper','research','AI-powered Google Search API for developers and AI agents.','🔍','https://serper.dev',true,false,2200),
('jina-ai','Jina AI','jina','research','AI search foundation platform for building neural search applications.','🔵','https://jina.ai',true,false,2400),
('cohere-embed','Cohere Embed','cohere-embed','research','AI text embedding API for semantic search and classification apps.','🔷','https://cohere.com/embeddings',true,false,1800),
('pinecone','Pinecone','pinecone','code','AI vector database for storing and querying embeddings at scale.','🌲','https://pinecone.io',true,false,3600),
('weaviate','Weaviate','weaviate','code','Open-source AI vector database with built-in ML model integration.','🔷','https://weaviate.io',true,false,2800),
('qdrant','Qdrant','qdrant','code','High-performance open-source vector database for AI similarity search.','🎯','https://qdrant.tech',true,false,2400),
('chroma-db','Chroma DB','chromadb','code','Open-source AI embedding database for building RAG applications.','🎨','https://trychroma.com',true,false,2100),
('milvus','Milvus','milvus','code','Open-source vector database built for scalable embedding similarity search.','🔷','https://milvus.io',true,false,1900),
('vectara','Vectara','vectara','research','AI pipeline platform for building search and RAG applications.','🔵','https://vectara.com',true,false,1600),
('llamacloud','LlamaCloud','llamacloud','research','LlamaIndex managed service for parsing, indexing, and RAG pipelines.','🦙','https://llamaindex.ai/llamacloud',false,false,1400)

ON CONFLICT (id) DO NOTHING;
